### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by MarkMaunder** [James-Thorson/VAST#10]
Running the code for the single species VAST from https://github.com/James-Thorson/VAST/blob/master/examples/VAST--single-species_example.Rmd I got the following compile error. 

> TmbList = Build_TMB_Fn("TmbData"=TmbData, "RunDir"=DateFile, "Version"=Version, "RhoConfig"=RhoConfig, "loc_x"=Spatial_List$loc_x, "Method"=Method)
Note: Using Makevars in c:/~/.R/Makevars 
Error in compile(paste0(Version, ".cpp")) : Compilation failed
In addition: Warning message:
running command 'make -f "C:/PROGRA~1/R/R-33~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" -f "C:\Users\mmaunder\AppData\Local\Temp\RtmpctHtF9\file24d83d3d4917" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="VAST_v2_0_0.dll" WIN=64 TCLBIN=64 OBJECTS="VAST_v2_0_0.o"' had status 127 
> compile(paste0(Version, ".cpp"))
Note: Using Makevars in c:/~/.R/Makevars 
Error in compile(paste0(Version, ".cpp")) : Compilation failed
In addition: Warning message:
running command 'make -f "C:/PROGRA~1/R/R-33~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" -f "C:\Users\mmaunder\AppData\Local\Temp\RtmpctHtF9\file24d8178711c" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="VAST_v2_0_0.dll" WIN=64 TCLBIN=64 OBJECTS="VAST_v2_0_0.o"' had status 127 
> Version
[1] "VAST_v2_0_0"

**Comment by James-Thorson** [comment]
In my experience, error code 127 (as you have) is a sign that TMB is not installed correctly on that machine. Could you please confirm whether you can compile any TMB cpp file, e.g., https://github.com/James-Thorson/mixed-effects/tree/master/linear_mixed_model

**Comment by MarkMaunder** [comment]
Jim,

I tried to compile the model you suggested and got the same issue. I reinstalled TMB (see below) and got the same issue. If I type “compile” I get the ADMB compile function so the TMB package has loaded. Any idea of what might be wrong?

trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.3/TMB_1.7.5.zip'
Content type 'application/zip' length 1937047 bytes (1.8 MB)
downloaded 1.8 MB

package ‘TMB’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\mmaunder\AppData\Local\Temp\Rtmpo7LD3i\downloaded_packages
>  library(TMB)
>  compile( 'C:\\Users\\mmaunder\\Documents\\Work\\IATTC\\2017 assessments\\Spatial models\\BET\\spacetime.cpp' )
Note: Using Makevars in c:/~/.R/Makevars
Error in compile("C:\\Users\\mmaunder\\Documents\\Work\\IATTC\\2017 assessments\\Spatial models\\BET\\spacetime.cpp") :
  Compilation failed
In addition: Warning message:
running command 'make -f "C:/PROGRA~1/R/R-33~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" -f "C:\Users\mmaunder\AppData\Local\Temp\Rtmpo7LD3i\file1a74e2a17d" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="C:\Users\mmaunder\Documents\Work\IATTC\2017 assessments\Spatial models\BET\spacetime.dll" WIN=64 TCLBIN=64 OBJECTS="C:\Users\mmaunder\Documents\Work\IATTC\2017 assessments\Spatial models\BET\spacetime.o"' had status 127
>

**Comment by James-Thorson** [comment]
I'm not following about 'compile' using the ADMB function, or how that
relates to confirming that TMB is installed.

My suggested steps are:
1.  Install latest version of R
2.  Install matching version of Rtools, while checking box to ensure that
Rtools is listed in the path
3.  install TMB from CRAN via `install.packages("TMB"`
4.  Check that it installed right using simple example (
https://github.com/James-Thorson/mixed-effects/tree/master/linear_mixed_model
)

I would only try VAST after TMB is confirmed to work in #4.

jim

**Comment by MarkMaunder** [comment]
Thanks Jim. I meant TBM not ADMB. I found a relevant issue on the TMB site that notes that the PATH needs the right gcc and rtools paths. I have an admb gcc and no rtools, so those are probably the issues.

**Comment by MarkMaunder** [comment]
Jim,

It works.

Thanks,

Mark
