### ISSUE TITLE
Change in most recent version of SpatialDeltaGLMM package causes error in multi-species vignette

### ISSUE THREAD

**Issue by michellesculley** [James-Thorson/VAST#101]
I'm working through the example multi-species model and have found an error in the setup for the QQ plots. The current vignette pastes the file location into the filename call, but the up-to-date SpatialDeltaGLMM QQ_Fn function has a specific input for the save location, causing the folder names to be duplicated in the file name. The proposed change to the vignette would be:

Q = SpatialDeltaGLMM::QQ_Fn(TmbData=TmbData, Report=Report, DateFile=DateFile, save_dir=DateFile, FileName_PP="Posterior_Predictive.jpg", FileName_Phist="Posterior_Predictive-Histogram.jpg", FileName_QQ="Q-Q_plot.jpg", FileName_Qhist="Q-Q_hist.jpg") 

I've tested this and can produce the QQ plots without an error.

**Comment by James-Thorson** [comment]
OK, please remove `SpatialDeltaGLMM` and re-install `VAST` and it should work.

**Comment by James-Thorson** [comment]
Oh, and you'll also have to use the updated multispecies vignette, on the "development" branch of package VAST
