### ISSUE TITLE
Error message when trying to run the multi-species example

### ISSUE THREAD

**Issue by agruss2** [James-Thorson/VAST#102]
I tried running the latest version of the multi-species example (which uses the version VAST_v4_1_0), but got an error message.
Therefore, I deleted the packages "VAST", "FishData", "SpatialDFA", "TMB", "TMBHelper", "SpatialDeltaGLMM", and "ThorsonUtilities" and tried re-running the multi-species example but still got the same error message:
```
Quitting from lines 257-258 (VAST--multispecies_example.Rmd) 
Error in tapply(bpred_ipos[which_ipos_in_y], INDEX = factor(TmbData$s_i[which_i_in_y_and_pos],  : 
  arguments must have same length
Calls: <Anonymous> ... withVisible -> eval -> eval -> <Anonymous> -> tapply
```
I actually got the same error message when running the model for counts for the "combined dataset study" today. I suspect that the problem comes from something within the "SpatialDeltaGLMM:::plot_residuals", which was recently modified (two months ago). 

Thanks a lot in advance for your help!

**Comment by James-Thorson** [comment]
OK, please remove `SpatialDeltaGLMM` and re-install `VAST` and it should work.
