### ISSUE TITLE
bug with VAST:: Crossvalidate_Fn

### ISSUE THREAD

**Issue by martin11112** [James-Thorson/VAST#103]
Hi Jim
I believe I found a bug in the function Crossvalidate_Fn. In the code, you use two loops with i as argument.
The issue is that results of all simulations are all stored in the second raw of the results table.
I would only change the argument of the second loop  (put a j instead of the i for example) and it should probably work.
Cheers
Martin

**Comment by James-Thorson** [comment]
Thanks now fixed.
