### ISSUE TITLE
issue with the function format_covariates

### ISSUE THREAD

**Issue by martin11112** [James-Thorson/VAST#104]
Hi Jim
Sometimes, I get Na's for some combinations knot/year with the function format_covariates.
It is usually happening when we have many knots. I investigated the issue and I believe it is coming from the fact that the code (1) searches the nearest knot related to every covariate sampling point and (2) then gives to every knot a value. With this kind of approach, you can have knots that are never selected as the nearest knot of a covariate sampling point. It will happen particularly when you have many knots and/or few covariates samples. you will finally get Na's in the outputs.

To avoid the issue, I think the code should have an opposite approach and (1) searches the nearest covariate sampling point related to every knots. With this kind of alternative approach, all knots will always receive a 'nearest covariate sampling point' and thus receive a value.

I coded a very ugly alternative version of the function. It is ugly as I use many loops ( I made it quickly and I am not superskilled with 'apply' stuff and multidimensional arrays). Anyway it is working for me so perhaps it could be useful.

format_covariates_new = function( Lat_e, Lon_e, t_e, Cov_ep, Extrapolation_List, Spatial_List, Year_Set=min(t_e):max(t_e)){
  
 
  
  if( is.vector(Cov_ep)) Cov_ep = matrix(Cov_ep,ncol=1) #step1 change format of coordinates
  
  if( is.numeric(Extrapolation_List$zone) ){
    Loc_e = SpatialDeltaGLMM::Convert_LL_to_UTM_Fn( Lon=Lon_e, Lat=Lat_e, zone=Extrapolation_List$zone, flip_around_dateline=Extrapolation_List$flip_around_dateline) 
     Loc_e = cbind( 'E_km'=Loc_e[,'X'], 'N_km'=Loc_e[,'Y'])
  }else{
    Loc_e = SpatialDeltaGLMM::Convert_LL_to_EastNorth_Fn( Lon=Lon_e, Lat=Lat_e, crs=Extrapolation_List$zone )
  }
  
  Cov_xtp = array(1, dim=c(length(Spatial_List$loc_x[,1]),length(Year_Set),ncol(Cov_ep))) #array with every knot/year/covariates combinaison  # Step 2: we Determine the nearest LatLon_e for each knot   
  for(pI in 1:ncol(Cov_ep)){
  for(y in 1:length(Year_Set)){ 
  
  num_year=which(t_e == Year_Set[y])     #subset years #1,#2,#3,#4,...
  Loc_e_sub=Loc_e[num_year,]  #we select the covariate data for this year 
  Cov_ep_sub=Cov_ep[num_year,]
  
  NN = RANN::nn2(data=Loc_e_sub, query=Spatial_List$loc_x, k=1 )$nn.idx[,1] 
  
  for (kn in 1:length(Spatial_List$loc_x[,1])){
  num=NN[kn] # num = the number of the row of the nearest covariate sampling point in Cov_ep_sub 
  Cov_xtp[kn,y,pI]= Cov_ep_sub[num]  
      } #
    } #
  } #
  
  
  colnames(Cov_xtp)=Year_Set     #change names of columns
  
  
  
  KnotVar_p = apply( Cov_xtp, MARGIN=3, FUN=function(vec){var(as.vector(vec))} ) # Step 3: Calculate variance lost when aggregating to knots
  DataVar_p = apply( Cov_ep, MARGIN=2, FUN=var )
  LostVar_p = 1 - KnotVar_p / DataVar_p
  var_p = matrix( c(KnotVar_p,DataVar_p,LostVar_p), nrow=3, byrow=TRUE)
  dimnames(var_p) = list( c("Variance_among_knots","Variance_among_observations","Proportion_of_variance_lost"), colnames(Cov_ep) )
  for(pI in 1:ncol(Cov_ep)){
    message( "Projecting to knots lost ", formatC(100*LostVar_p[pI],format="f",digits=1), "% of variance for variable ", ifelse(is.null(colnames(Cov_ep)[pI]),pI,colnames(Cov_ep)[pI]))
  }
  
  
  Return = list( Cov_xtp=Cov_xtp, var_p=var_p ) # Calculate interpolated value
  return( Return )
}
``
Cheers
Martin

**Comment by James-Thorson** [comment]
Thanks for recording this here.  I think that I want the default behavior to remain as-is, but agree that other circumstances may require users to build their own function.
