### ISSUE TITLE
Memory allocation 

### ISSUE THREAD

**Issue by MarkMaunder** [James-Thorson/VAST#11]
Is there a way to set the memory allocation in VAST? I get this error after running the model for a long time

outer mgc:  63.42044 
iter: 1  value: 299032.3 mgc: 6.017701e-05 ustep: 1 
iter: 2  value: 299032.3 mgc: 7.166481e-08 ustep: 1 
iter: 3  mgc: 6.286855e-15 
outer mgc:  63.38675 
Error: cannot allocate vector of size 2.7 Gb

**Comment by James-Thorson** [comment]
Yeah, that's probably during the bias-correction phase.

Do you have the line:

TMBhelper::Optimize( ... bias.correct=TRUE )

...?

The easiest fix is to turn off bias-correction.  I'm happy to discuss other
options if you can confirm that turning off bias-correction fixes the
problem (so we know that that is the problem)

**Comment by MarkMaunder** [comment]
No, I have 

TMBhelper::Optimize( ... bias.correct=FALSE)

**Comment by MarkMaunder** [comment]
I reduced the size of the data set and it worked
