### ISSUE TITLE
Adding structure to beta1_ct

### ISSUE THREAD

**Issue by EllenY** [James-Thorson/VAST#111]
My data is characterized by 1) counts, 2) missing one year, and 3) 100% encounter in 4 of 14 years in the time series.

I am trying to implement Option 3 or 4 from  https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/What-to-do-with-a-species-with-0%25-or-100%25-encounters-in-any-year

How do I add structure to the year effect?

Map_customized $beta1_ct<-

**Comment by James-Thorson** [comment]
Thanks for posting this comment.  I see that you are using `ObsModel[2]=3` and temporal structure on intercepts for the first linear predictor, `RhoConfig[1]!=0`.  These options are not coded to work together, and I have added an informative error message to `Data_Fn` for this case.  Please try changing to `ObsModel[2]=3` and `RhoConfig[1]=0`
