### ISSUE TITLE
"The model is likely not converged" in Multispecies Example.

### ISSUE THREAD

**Issue by andrewdeines** [James-Thorson/VAST#112]
I'm attempting to follow the multispecies example out of the box. The call to TMBhelper::Optimize() finishes with the above convergence message.  Running down the error from TMBhelper indicates that the issue is from the max_gradient>0.0001 (indeed, Opt$max_gradient = 0.00899).  My TMB installation checks out (according to https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/Steps-to-install-TMB).
Is this expected behavior from the example?

**Comment by James-Thorson** [comment]
It took a few runs to notice that `newtonsteps` was in the wrong place in `TMBhelper::Optimize` and therefore the convergence was not as tight as I recommend.  Now fixed, results are unchanged.
