### ISSUE TITLE
Interpretation of reduced-rank interaction matrix

### ISSUE THREAD

**Issue by skivela** [James-Thorson/VAST#113]
I included species interactions in a VAST model with Rank = 4, while I have 5 species in the data. Consequently, the interaction matrix B_cc is a 4x4 matrix. How can I interpret the interaction matrix when its rank is less than the number of species?

**Comment by James-Thorson** [comment]
I understand that you're using the settings from here: https://github.com/James-Thorson/VAST/wiki/Species-interactions-in-VAST

Those settings turn on an additional parameter (average 1st order autocorrelation), which is added in when calculating B_pp.  Lower rank decreases the number of degrees of freedom that must be estimated (see Thorson Munch Swain 2017 for formula and rationale), but autocorrelation (or a random-walk structure) ensures that the Nspecies-Rank axes which would have a 0 eigenvalue instead have an eigenvalue equal to the autocorrelation parameter (or 1.0 when using a random-walk structure).

B_pp is used to premultiply the state-vector (again see Thorson Munch Swain 2017).  So e.g. if the 2nd row 1st column of B_pp (`B_pp[2,1]`) is beta, then this indicates that a 1% change in density for species 1 is predicted to cause a beta change in per-capita productivity for species 2.
