### ISSUE TITLE
Covariates that are constant across knots

### ISSUE THREAD

**Issue by perretti** [James-Thorson/VAST#115]
Hi Jim,

Whenever I include a covariate that is constant across space (i.e., shelf-wide temperature) I'm getting singularity errors in Optim. I'm wondering if this is because of how I'm setting it up in X_xtp. I repeat the shelf-wide temperature for each knot, so the slice of X_xtp for that covariate is a repeated value in each row that changes in each column. I.e.: 
```
| 1  | 4 | 2 |
| 1  | 4 | 2 |
| 1  | 4 | 2 |
| 1  | 4 | 2 |
```
Is that incorrect?

Thanks for your help.

**Comment by James-Thorson** [comment]
You can always use TMBhelper::Check_Identifiable to track down a
singularity.  However, off the top of my head, I'd assume its because
annual covariates are singular with your intercepts.  What are you
specifying for RhoConfig?  Annual covariates require some structure (!=0)
for beta1 and beta2 slots

**Comment by perretti** [comment]
That makes sense, and yep that was it. Thanks.

**Comment by perretti** [comment]
Actually I am still running into problems with this. I simplified the model by removing all covariates, and setting the intercepts to be a random walk, and when I run TMBhelper::Check_Identifiable(obj = Obj) I get the error 
```
 Error in apply(List[["Eigen"]]$vectors[, List[["WhichBad"]]], MARGIN = 1,  : 
  dim(X) must have a positive length
```

So I'm guessing I'm setting something up wrong. Here is how I set up the configs:

`FieldConfig <- c("Omega1"   = "IID", 
                 "Epsilon1" = "IID", 
                 "Omega2"   = "IID", 
                 "Epsilon2" = "IID")`
`RhoConfig <- c("Beta1"    = 2,
               "Beta2"    = 2, 
               "Epsilon1" = 0, 
               "Epsilon2" = 0)`
`OverdispersionConfig <- c("Delta1" = 0, 
                          "Delta2" = 0)`
`ObsModel <- c("PosDist" = 2,
              "Link"    = 0)`

Thanks for any help.

**Comment by James-Thorson** [comment]
its possible its a problem with `TMBhelper::Check_Identifiable`.  If you use those settings and run the model, do you get a singular hessian?

**Comment by perretti** [comment]
Hmmm, well I just re-ran Check_Identifiable and now it is working, so maybe I hadn't updated my inputs. But when I run it (without covariates) I get:

          Param        MLE Param_check
1    ln_H_input  0.0000000          OK
2    ln_H_input  0.0000000          OK
3     lambda1_k  0.0000000          OK
4    L_omega1_z  1.0000000         Bad
5    L_omega1_z  1.0000000         Bad
6  L_epsilon1_z  1.0000000         Bad
7  L_epsilon1_z  1.0000000         Bad
8     logkappa1 -0.1053605         Bad
9    logsigmaB1  0.0000000          OK
10    lambda2_k  0.0000000          OK
11   L_omega2_z  1.0000000         Bad
12   L_omega2_z  1.0000000         Bad
13 L_epsilon2_z  1.0000000         Bad
14 L_epsilon2_z  1.0000000         Bad
15    logkappa2 -0.1053605         Bad
16   logsigmaB2  0.0000000          OK
17    logSigmaM  1.6094379          OK
18    logSigmaM  1.6094379          OK

So it doesn't like something about the way the random fields are set up.  But when I run TMBhelper::Optimize it runs fine, and the convergence checks come back fine. So perhaps this is a problem with Check_Identifiable. 

Let me know what you think about that. My next step is to figure out why it chokes when I include some covariates.

**Comment by James-Thorson** [comment]
yeah, Check_Identifiable is not well documented obviously.  I think you need to run it after doing optimization, which it appears you didn't do here.  So its not behaving as expected.  I should add some more docs and warnings I s'pose ;)

but yes, try adding spatially-constant-annually-varying covariates back with some temporal structure on intercepts

**Comment by perretti** [comment]
I added the annual covariate back in and after running for a while the optimizer kicks out:

`
iter: 1  Error in iterate(par) : 
  Newton dropout because inner gradient had non-finite components.`
`outer mgc:  NaN 
`
`Error in optimHess(par = ParHat, fn = obj$fn, gr = obj$gr) : 
  gradient in optim evaluated to length 1 not 34
`

**Comment by James-Thorson** [comment]
did you standardize the covariate to have a SD of 1.0?  You can get numerical over/underflow easily with nonstandardized covariates (particularly using previous versions of the Poisson-link delta model, which I recently changed to make more numerically stable).

**Comment by perretti** [comment]
Thanks, Jim. It works now that I've standardized all of the annual covariates.
