### ISSUE TITLE
How to “turn off” covariate estimations for encounter probability

### ISSUE THREAD

**Issue by mkajanus** [James-Thorson/VAST#117]
I am trying to estimate data with 100% encounter probability with the model settings below:
FieldConfig = c("Omega1"=0, "Epsilon1"=0, "Omega2"=1, "Epsilon2"=1) 
RhoConfig = c("Beta1"=0, "Beta2"=3, "Epsilon1"=0, "Epsilon2"=4) 
ObsModel = c(2,3)  
Using RhoConfig[1]=0 removes the estimation of the intercept for encounter probability. However, the effect of the covariate on the encounter probability (gamma1_ctp) is still included in the parameter estimates. I would be interested only on the effect of the covariate on the positive catch rate. So the questions are:
(1)   Does gamma1_ctp  "mask" or bias some of the effect of gamma2_ctp on the positive catch rate?
(2)   Is there a way in VAST to also “turn off” covariate estimations for the encounter probability?

Thank you in advance.

**Comment by James-Thorson** [comment]
There's no simplified interface for doing this.

Instead, you need to build the object, modify the `Map` object that turns off parameters, and then rebuild the object with the new `Map`.  To do so, please
```R
Obj = Build_TMB_Fn( ... )
Map = Obj$Map
Map[["gamma1_ctp"]] = factor( array(NA, dim=dim(Obj$Parameters$gamma1_ctp)))
Obj = Build_TMB_Fn( ..., Map=Map )
```
Further details about the `Map` input can be read via the code for `Build_TMB_Fn` and dependent functions, and please see the user manual or `?Param_Fn` to link parameters named in `Obj$Parameters` to their model usages
