### ISSUE TITLE
how to use non-Euclidean distances

### ISSUE THREAD

**Issue by scrmc** [James-Thorson/VAST#118]
Hi,
Is it possible to use a matrix of hydrological distances instead of the matrix of Euclidean distances? If so how can I do it?

Thank you,
Sara Carona

**Comment by James-Thorson** [comment]
We are currently adding an option to use an exponential correlation function on stream networks, based on recent research that didn't use VAST: https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/eap.1767.  The first iteration of the new feature is technically available in VAST, but has essentially no testing or documentation.  I recommend either (1) check back in 6 months, (2) email me individually for an example script, or (3) email me personally to be introduced to the post-doc working on the project.  I will not be providing any support for this feature until it is fully documented.
