### ISSUE TITLE
SpatialDeltaGLMM::Plot_data_and_knots does not work

### ISSUE THREAD

**Issue by MarkMaunder** [James-Thorson/VAST#12]
Running the command

SpatialDeltaGLMM::Plot_data_and_knots(Extrapolation_List=Extrapolation_List, Spatial_List=Spatial_List, Data_Geostat=Data_Geostat, PlotDir=DateFile )

does not produce a plot. I get the output

 Loading required package: maps
Loading required package: mapdata
null device 
          1

**Comment by MarkMaunder** [comment]
I used
Options =  c("SD_site_density"=1, "SD_site_logdensity"=0, "Calculate_Range"=0, "Calculate_evenness"=0, "Calculate_effective_area"=0, "Calculate_Cov_SE"=0, 'Calculate_Synchrony'=0, 'Calculate_Coherence'=0)

**Comment by James-Thorson** [comment]
you could skip that plot -- its probably a difference in formatting
for `Data_Geostat`.
 its just supposed to help visualize your data anyway, so not too important.

**Comment by MarkMaunder** [comment]
Jim,

Actually, none of the plots work. I did get the table of indices and they looked OK.

What I want to do is estimate the average density by 1x1 square to use for the relative abundance by area. What object is that stored in?

Thanks,

Mark

**Comment by afredstonhermann** [comment]
A note for anyone else getting the "null device" error with `plot_data` (which I've gotten on a PC trying to follow the VAST example scripts): all of the plotting code is in [FishStatsUtils](https://github.com/James-Thorson-NOAA/FishStatsUtils/tree/master/R) and you can easily copy the actual `plot()` code to explore the data, generate plots, and save them however you like without needing the `plot_data` function.

**Comment by James-Thorson-NOAA** [comment]
Thanks Alexa.

Are you using the high-level wrapper functions (https://github.com/James-Thorson-NOAA/VAST/wiki/Simple-example) or the mid-level functions in the soft-deprecated Rmd scripts (https://github.com/James-Thorson-NOAA/VAST/tree/master/examples).  I'd be particularly keen to fix any issues in the former, if you have time and interest to elaborate on the problem you're getting.

**Comment by afredstonhermann** [comment]
It's the former--I was following the "Simple example" that you linked. I don't really know how to troubleshoot the error, but since it says "null device" and I can generate the plots on my own by using the plotting script from the function code, I suspect that it is related to writing out and saving the plots. 

Here's what I pulled out of the `plot_data` source code in the meantime, which works great: 

```
Lat_i=Data_Geostat[,'Lat']
Lon_i=Data_Geostat[,'Lon']
Year_i=Data_Geostat[,'Year']

plot( Extrapolation_List$Data_Extrap[which(Extrapolation_List$Area_km2_x>0),c('Lon','Lat')], cex=0.01, main="Extrapolation (Lat-Lon)" )
    map( "world", add=TRUE )

    plot( Extrapolation_List$Data_Extrap[which(Extrapolation_List$Area_km2_x>0),c('E_km','N_km')], cex=0.01, main="Extrapolation (North-East)" )
    
    plot( Spatial_List$loc_x, col="red", pch=20, main="Knots (North-East)")

Year_Set = min(Year_i):max(Year_i)
    Nrow = ceiling( sqrt(length(Year_Set)) )
    Ncol = ceiling( length(Year_Set)/Nrow )
    par( mfrow=c(Nrow,Ncol), mar=c(0,0,2,0), mgp=c(1.75,0.25,0), oma=c(4,4,0,0) )
    for( t in 1:length(Year_Set) ){
      Which = which( Year_i == Year_Set[t] )
      plot( x=Lon_i[Which], y=Lat_i[Which], main=Year_Set[t], xlim=range(Lon_i), ylim=range(Lat_i), xaxt="n", yaxt="n")
      map( "world", add=TRUE, fill=TRUE, col="grey" )
      if( t>(length(Year_Set)-Ncol) ) axis(1)
      if( t%%Ncol == 1 ) axis(2)
      mtext( side=c(1,2), text=c("Longitude","Latitude"), outer=TRUE, line=1)
    }
```

**Comment by James-Thorson-NOAA** [comment]
Well, its a bit of a mystery to me ;) but thanks for flagging this issue, and also for solving it on your own for your purposes!  And this record on the issue tracker is useful for me to track bugs, in case someone else identifies the same issue.
