### ISSUE TITLE
Update single species example for new observation error structure

### ISSUE THREAD

**Issue by cstawitz** [James-Thorson/VAST#120]
It looks like in the newest version of VAST, `Data_fn` has an `ObsModel_ez` argument, which is a matrix with e x 2 dimensions, while the examples and user manual reference the argument `ObsModel`, which is a 1x2 vector. Do you have a working example using the new matrix structure you can share for reference?

If I try to run `Data_Fn` with `ObsModel_ez=c(3,0)`, I receive an error:
```
Error in Data_Fn(Version = Version, FieldConfig = FieldConfig, OverdispersionConfig = OverdispersionConfig,  : 
  Some years and/or categories have either all or no encounters, and this is not permissible when ObsModel_ez[,'Link']=0
```
however I have no encounter probabilities.

**Comment by James-Thorson** [comment]
A few responses:

1.  Data_Fn uses partial matching to take ObsModel and match it to argument ObsModel_ez.  If given a vector, it automatically coerces it to a 1x2 matrix.  Arnaud Gruss is the main users of this feature so far.
2.  I imagine its warning you that you have some year where all of your data are non-zero
3.  I don't think ObsModel_ez = c(3,0) is a valid option (I should probably add an informative error message), please see `?VAST::Data_Fn` for allowable options.  Do you mean ObsModel_ez = c(0,3), where the ObsModel_ez[,3] indicates that you want it to turn off the presence/absence component of the model?

**Comment by cstawitz** [comment]
I don't understand the description of the observation model argument to the `Data_Fn` function, hence why I think an update to the examples or user manual would be helpful. For example, it says "an optional matrix with two columns where first column specifies the distribution for positive catch rates, and second element specifies the functional form for encounter probabilities" 

I interpreted this to mean the second column was the one I needed to turn off, as I don't have encounter probabilities. Also, it is unclear what "e" is as it refers to row number in the ObsModel matrix.

Also, if I use `ObsModel_ez = c(0,3)` I get the same error. It only works if I have non-zero values for both elements in the `ObsModel_ez`

**Comment by James-Thorson** [comment]
I apologize:  when I added the feature for multiple data types (i.e., multiple rows of `ObsModel_ez`), I see that I broke the error-check for 0% and 100% encounter data.  I fixed this in a push just now, please re-install VAST and try again using `ObsModel[2]=3`.  

Yes, I agree that the documentation for multiple data types should be improved, and we plan to when further along in that project.

**Comment by cstawitz** [comment]
Thanks, Jim! I'll double check it fixes the issue tomorrow morning.

**Comment by cstawitz** [comment]
Just to make sure this isn't lost - reminder to change line 150 of `Data_Fn` to: `if( any(Prop_nonzero==0|Prop_nonzero==1) & any(ObsModel_ez[,2]==0) ){`

I still have to run this off a local forked copy to deal with zero observations.

**Comment by James-Thorson** [comment]
This is already added in the development branch which you can install using `devtools::install_github("james-thorson/VAST", ref="development")`, it'll merge to main branch when I finish developing and testing that newest VAM feature
