### ISSUE TITLE
Rerun_Fn bug fix

### ISSUE THREAD

**Issue by perretti** [James-Thorson/VAST#123]
Currently returns error: `Error in as.vector(x) : object 'parhat' not found`

Fixed by changing cov_to_turnoff = 1:dim(**parhat**[["gamma2_ctp"]])[3]  

to 

cov_to_turnoff = 1:dim(**parhat0**[["gamma2_ctp"]])[3]

in the formals.

**Comment by James-Thorson** [comment]
Thanks!  I'll add this change to my next development-version commit, and it will merge to main branch next time I pull the development-version in.  So it'll be a few weeks before its fixed in main branch, but will be fixed soon.
