### ISSUE TITLE
Please report error to package author in PlotIndex

### ISSUE THREAD

**Issue by kvert-pre** [James-Thorson/VAST#126]
When running these lines of code, 

> Year_Set<-unique(BDDi$Year)
> Years2Include<-which( Year_Set %in% sort(unique(Data_Geostat[,'Year'])))
> Index = SpatialDeltaGLMM::PlotIndex_Fn( DirName=DateFile, TmbData=TmbData, Sdreport=SD, Year_Set=Year_Set, Years2Include=Years2Include, strata_names=strata.limits[,1], use_biascorr=TRUE, category_names=levels(Data_Geostat[,'spp']) )

I get the error 
Error in SpatialDeltaGLMM::PlotIndex_Fn(DirName = DateFile, TmbData = TmbData,  : 
  You appear to be using bias-correction, but all values are NA. Please report problem to package author.

Does that mean something is wrong with the bias-corrected Index values ? 

Best 
Katyana

**Comment by James-Thorson** [comment]
Hmm.  I don't know why that would have happened.  Please check over your bias correction in more detail, I can't offer more advice without looking at your code (which I don't have time to do for 3-4 weeks).  One place to look is the `bias.correct.control` input in `TMBhelper::Optimize( ..., bias.correct.control=X )`

**Comment by kvert-pre** [comment]
Thank you.

Best
Katyana
