### ISSUE TITLE
Recommended changes in the "Simulator" page of the Wiki

### ISSUE THREAD

**Issue by agruss2** [James-Thorson/VAST#129]
@James-Thorson 
I would recommend two changes in the "Simulator" page of the Wiki, because of the recent changes you introduced in VAST, particularly the use of the new package "FishStatsUtils".  
(1) I would have initially recommended to replace:
```
Version = SpatialDeltaGLMM::get_latest_version( package="VAST" )
```
with:
```
Version = get_latest_version( package="VAST" )
```
However, for some reason, the optimization step does not work with the latest version of VAST, so I would recommend the following change instead:
```
Version = "VAST_v4_4_0"
```
(2) Then, this line of code:
```
data( EBS_pollock_data, package="SpatialDeltaGLMM" )
```
should  be replaced with:
```
data( EBS_pollock_data )
```
Many thanks!

**Comment by James-Thorson** [comment]
done some, will sort out the version issue later.
