### ISSUE TITLE
Function changed name

### ISSUE THREAD

**Issue by kellijohnson** [James-Thorson/VAST#131]
https://github.com/James-Thorson/VAST/blob/1b49b900e047cdb7f34b4e5a83ed11fb90866761/R/calculate_proportion.R#L65

The function should be `FishStatsUtils::plot_lines`

Not sure if any of the arguments changed as well because `FishStatsUtils::plot_lines` is not working for my model (based on the multispecies example in the test folder) after changing the function name.

**Comment by James-Thorson** [comment]
Already fixed in the development branch while I'll merge soon.  Please use that for now.
