### ISSUE TITLE
Add reference to package on Build_TMB_Fn line 66

### ISSUE THREAD

**Issue by cstawitz** [James-Thorson/VAST#132]
A number of times I have run into masking issues because I loaded the `compiler` library after TMB, and `compile` is a function both in `TMB` and `compiler` and both are dependencies of VAST. This results in `compile` calling `compiler::compile` instead of `TMB::compile`

This could easily be prevented by replacing `compile` with `TMB::compile` on line 66 (maybe other places too)

**Comment by James-Thorson** [comment]
I don't want to do this so I can use TMBdebug::compile depending on which is loaded.  I assume the advanced users can sort this out ;)

**Comment by cstawitz** [comment]
Well, I figured it out, but it took several hours the first time. And then it has happened twice since..

You could put an if statement afterwards, i.e. if there are no .dll files in the directory then call `TMB::compile`.

**Comment by cstawitz** [comment]
Also, this is explicitly recommended as a best practice for package
development:
http://r-pkgs.had.co.nz/description.html
