### ISSUE TITLE
Trouble with SpatialDeltaGLMM

### ISSUE THREAD

**Issue by mkajanus** [James-Thorson/VAST#133]
I have used VAST over the past 6 months and it has ran smoothly. However, recently there have been problems arising. I tried to run VAST after a few days brake with the same computer, installations, data and model settings, but I suddenly received the following error message:
 
“There is no package called SpatialDeltaGLMM”
 
I re-installed SpatialDeltaGLMM separately by following the instructions on your GitHub –page.

install_github("nwfsc-assess/geostatistical_delta-GLMM", ref="3.3.0") 

However, this SpatialDeltaGLMM is version 1.0. (2014-10-25) and it does not include e.g. the function “Prepare_Extrapolation_Data_Fn”, which is needed in the derivation of the spatial mesh. It seems that SpatialDeltaGLMM version 3.4.0 (2016-08-09) includes the “Prepare_Extrapolation_Data_Fn” function, but I wonder why I did not get the latest version of SpatialDeltaGLMM when re-installing the package. I also tried removing all packages and re-installing VAST. However, I still did not get the latest version of SpatialDeltaGLMM.
 
After re-installing VAST, it first appeared to be possible to proceed with your current VAST multispecies example available in GitHub, which does not use SpatialDeltaGLMM (but instead has the functions “make_extrapolation_info” and “make_spatial_info”). However, now with my laptop (that has SpatialDeltaGLMM version 3.4.0) there is no function “make_extrapolation_info”, but the analysis runs instead with “Prepare_Extrapolation_Data_Fn” function that uses SpatialDeltaGLMM. I am sorry, but I find all of this a bit confusing.

Which version of SpatialDeltaGLMM is adviced to be used with VAST and how could that be installed?

Thank you for your advice.

**Comment by James-Thorson** [comment]
This is quite a mix of questions.  I don't know which is most important, so please organize issues a bit more carefully in the future.

> Which version of SpatialDeltaGLMM is adviced to be used with VAST and how could that be installed?
I no longer maintain SpatialDeltaGLMM and users are recommended to switch to VAST (which has all features plus more).  

> It seems that SpatialDeltaGLMM version 3.4.0 (2016-08-09) includes the “Prepare_Extrapolation_Data_Fn” function, but I wonder why I did not get the latest version of SpatialDeltaGLMM when re-installing the package. 
Perhaps try `devtools::install_github("nwfsc-assess/geostatistical_delta-GLMM", ref="3.5.0")` which should include all important code prior to the recent re-factoring to add `FishStatsUtils`.

**Comment by mkajanus** [comment]
Thank you for your reply. I apologize for the unclear description of the problem.

Also, thank you for the instructions. Installing SpatialDeltaGLMM with the code you provided here, did indeed install the 3.4.0 version of the package.

Best,
Mira
