### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by mvo13** [James-Thorson/VAST#134]
**We are trying to install ‘VAST’ on several windows machines. It worked fine before, but now we are facing some difficulties during the installation

When starting the process such as:**

_install_github("james-thorson/VAST")_ 

**downloading initiates normally:**

_Downloading GitHub repo james-thorson/VAST@master_

**but then, while downloading ‘FishStatsUtils’** 

_Downloading GitHub repo james-thorson/FishStatsUtils@master_

**there is a automatic redirection to get ‘INLA’ from the Norwegians but the link is unavailable**

_Installing 2 packages: formatR, pander

Error: (converted from warning) unable to access index for repository https://www.math.ntnu.no/inla/R/stable/src/contrib:
  cannot open URL 'https://www.math.ntnu.no/inla/R/stable/src/contrib/PACKAGES'
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
3: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
4: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers_

### which leads to a stop of the entire installation process.

**Can’t seem to get it installed without the ‘FishStatsUtils’ bit.
Loading ‘INLA’ separately does not help either.**

**We are unable to get past this. We did not have this problem until very recently. Are you aware of similar difficulties? Is there a way to get past this?

Thanks**

**Comment by James-Thorson** [comment]
If having this problem, please try installing INLA first, and only when its installed try to install VAST.  Please refer to the INLA website to trouble shoot installation problems with it.  I remember having some problems on a machine, and finding it easier to download their tarball (tar.gz or whatever) and installing that manually through the install-packages click-through options in R.

**Comment by mvo13** [comment]
Hi,
thanks for your reply.

The problem is that I have installed INLA and added to the library. But
it's not working.

The weird thing is that the installation process was all running super fine
on other machines before and for some reason this problem is occuring now...

Any ideas what the reason might be that INLA does not get recognized?

Cheers

Am Mi., 31. Okt. 2018 um 15:22 Uhr schrieb Jim Thorson <
notifications@github.com>:

**Comment by smormede** [comment]
I just had a similar problem. Looks like INLA has moved homes, now to load it requires the following (be good to update on the VAST front page) 

install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
