### ISSUE TITLE
VAST installation failing to find INLA url

### ISSUE THREAD

**Issue by smormede** [James-Thorson/VAST#137]
I tried to upload the new version of VAST (I was running on 4.4.0) and got a compile error. I tracked that down to different versions of packages (I had R3.4.3). I uploaded R v 3.5.1.

I tried to upload INLA using the instructions in VAST but it looks like it has moved, see:
http://www.r-inla.org/download

I tried to re-load VAST (which had loaded before), and got the following error
> devtools::install_github("james-thorson/VAST")
Downloading GitHub repo james-thorson/VAST@master
Downloading GitHub repo james-thorson/FishStatsUtils@master
Installing 2 packages: formatR, pander
Installing packages into ‘C:/Users/mormedes/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Error: (converted from warning) unable to access index for repository https://www.math.ntnu.no/inla/R/stable/src/contrib:
  cannot open URL 'https://www.math.ntnu.no/inla/R/stable/src/contrib/PACKAGES'

It might be linked to the relocation of INLA?

**Comment by James-Thorson** [comment]
for now I think I'll just need people to assure that they've installed INLA prior to VAST.  I'll try to investigate but it will likely be slow.

**Comment by smormede** [comment]
INLA was installed already using the new link. It looks like VAST is still looking for the INLA repository which I assume has been moved.

**Comment by James-Thorson** [comment]
can you instead install FishStatsUtils individually first, and see if that triggers the error, or if its VAST in particular?

**Comment by smormede** [comment]
OK I'm confused. Now it looks like VAST is installing, but when I run make_spatial_info I get the following error:
{...}
Num=100 Current_Best=12639092.2 New=11727368.5
Calculated and saved to C:\Users\mormedes\OneDrive - NIWA\Projects\Specific_Projects\2018\EndANT\VAST\R6.81\/Kmeans-100.RData
Error in inla.call.builtin() : INLA installation error; no such file

**Comment by James-Thorson** [comment]
It seems like inla is not installing propoerly. I recommend d clicking
through the directories at the install URL, downloading the zip for your r
versio and os and installing locally from zip
