### ISSUE TITLE
cc1plus.exe out of memory - compilation error

### ISSUE THREAD

**Issue by TiffanyVidal** [James-Thorson/VAST#138]
I am trying to run the example code for single and multi species VAST models. When I run the Build_TMB_Fn line I receive the following error:
cc1plus.exe: out of memory allocating 8388572 bytes
make: *** [//env/enterprise/MYDOCU~1/R/R-35~1.0/etc/i386/Makeconf:215: VAST_v5_2_0.o] Error 1
Error in compile(paste0(Version, ".cpp")) : Compilation failed

Any thoughts on what this is telling me or how to troubleshoot? I'm on a Windows 7 machine. I can run other TMB models without issue. Thank you

**Comment by James-Thorson** [comment]
That's a new one to me! What other VAST models gave you been able to run?

**Comment by TiffanyVidal** [comment]
No other VAST models, just other TMB models - e.g. GLMMs.

**Comment by James-Thorson** [comment]
How much memory does your machine have?

**Comment by TiffanyVidal** [comment]
16 GB

**Comment by James-Thorson** [comment]
Well, that's a new error to me.  Its occurring during compilation, so you could consider posting on the TMB issue tracker.  You could also try other CPP versions of VAST (particularly latest stable release VAST_v5_3_0) to see if you can identify whether its all of them, or just `VAST_v5_2_0`.

**Comment by ballengerj** [comment]
Did anyone ever find a solution to this issue? I get the same error, running the correct installation verification example from the github site. Here is the specific error.

### Making TMB object
C:/Rtools/mingw_32/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG -IC:/Users/BALLEN~1/DOCUME~1/RPACKA~1/TMB/include -IC:/Users/BALLEN~1/DOCUME~1/RPACKA~1/RCPPEI~1/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_VAST_v9_2_0  -DTMB_LIB_INIT=R_init_VAST_v9_2_0          -O2 -Wall  -mtune=core2 -c VAST_v9_2_0.cpp -o VAST_v9_2_0.o

cc1plus.exe: out of memory allocating 65536 bytes
make: *** [C:/PROGRA~1/R/R-36~1.3/etc/i386/Makeconf:215: VAST_v9_2_0.o] Error 1
Error in TMB::compile(paste0(Version, ".cpp")) : Compilation failed

I've verified and can run TMB examples outside of VAST with no issues.

**Comment by ballengerj** [comment]
FYI, I determined that when I updated R and R Studio it somehow got set to use the 32-bit version of R. When I changed to using the 64-bit, which it should have been, it worked fine.
