### ISSUE TITLE
Summarize function fixes

### ISSUE THREAD

**Issue by John-R-Wallace** [James-Thorson/VAST#139]
In the Summarize() function:

    Summarize <- function (obj)     
    {
        report = obj$report()
        parhat = obj$env$parList()
        D_xct = Report$D_xct
        Return = list(parhat = parhat, D_xct = D_xct)
        return(Return)
    } 
 
'report' in lines 3 and 5  have a different case.

'Line 5 would find 'Report' in the Global Environment if:

     Report = Obj$report()

was called before Summarize()

Also, 'Report$D_xct' now appears to be 'Report$D_xcy'

Lastly, setting a default of  'Obj' for 'obj' would also avoid having to use:

    Summarize(Obj) 

instead of Summarize() for those who use 'Obj' for the name of their objective function list.

And so, a working Summarize() function is:

    Summarize <- function (obj = Obj) 
    {
        Report = obj$report()
        parhat = obj$env$parList()
        D_xcy = Report$D_xcy
        Return = list(parhat = parhat, D_xcy = D_xcy)
        return(Return)
    }

**Comment by James-Thorson** [comment]
I am fixing the case of `report` in the development branch, but not changing the default behavior for inputs (having inputs draw from global environment is not standard for R functions)
