### ISSUE TITLE
plot_factors

### ISSUE THREAD

**Issue by jin-gao** [James-Thorson/VAST#14]
The covariance Cov_jj passed to SpatialDFA::Rotate_Fn may be rank deficient. I changed Line 38 to L_pj = t(chol(Cov_jj,pivot=TRUE))[,1:Nfactors] in SpatialDFA::Rotate_Fn to get the Cholesky decomposition for positive semi-definite matrix.

**Comment by James-Thorson** [comment]
I have now fixed `Plot_factors` to use the Cholesky estimated by VAST, rather than converting to and from the rank-reduced covariance (which was numerically instable).  Should be fixed now
