### ISSUE TITLE
Error using devtools::install_github("james-thorson/VAST")

### ISSUE THREAD

**Issue by sea521** [James-Thorson/VAST#143]
I removed the old VAST package in my RStudio and tried to install VAST again with "devtools::install_github("james-thorson/VAST")". I got some error message:

> > install_github("james-thorson/VAST")
Downloading GitHub repo james-thorson/VAST@master
James-Thorson-VAST-2f16e27/inst/doc/user_manual.pdf: truncated gzip input
tar.exe: Error exit delayed from previous errors.
Error: Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -zxf "C:\Users\fish521\AppData\Local\Temp\RtmpQrNQ1w\file332430f94f16.tar.gz" -C "C:/Users/fish521/AppData/Local/Temp/RtmpQrNQ1w/remotes33247ea343b"’ returned error code 1
2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -ztf "C:\Users\fish521\AppData\Local\Temp\RtmpQrNQ1w\file332430f94f16.tar.gz"' had status 1

Also I tried to install FishStatsUtils and got similar error.

> install_github("james-thorson/FishStatsUtils")
Downloading GitHub repo james-thorson/FishStatsUtils@master
James-Thorson-FishStatsUtils-89b6511/data/chatham_rise_grid.rda: truncated gzip input
tar.exe: Error exit delayed from previous errors.
Error: Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -zxf "C:\Users\fish521\AppData\Local\Temp\RtmpQrNQ1w\file3324732553ab.tar.gz" -C "C:/Users/fish521/AppData/Local/Temp/RtmpQrNQ1w/remotes332479f35d1"’ returned error code 1
2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -ztf "C:\Users\fish521\AppData\Local\Temp\RtmpQrNQ1w\file3324732553ab.tar.gz"' had status 1

Thanks!

**Comment by James-Thorson** [comment]
I can't replicate this error. What OS and R version? Can you remove and reinstall devtools, and try another R version, and then report back?

**Comment by Mahdi2022** [comment]
### I tried to install the new version of the VAST package and FishstatsUtils in Rstudio1.1.453 with the following code, but I got the error message:
devtools::install_github("james-thorson/VAST")
Error: package or namespace load failed for 'FishStatsUtils':
.onAttach failed in attachNamespace() for 'FishStatsUtils', details:
call: contrib.url(repos, "source")
error: trying to use CRAN without setting a mirror
Error: loading failed
Execution halted
*** arch - x64
Error: package or namespace load failed for 'FishStatsUtils':
.onAttach failed in attachNamespace() for 'FishStatsUtils', details:
call: contrib.url(repos, "source")
error: trying to use CRAN without setting a mirror
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'

removing 'C:/Program Files/R/R-3.5.2/library/FishStatsUtils'
In R CMD INSTALL
Error in i.p(...) :
(converted from warning) installation of package ‘C:/Users/MAMINI~1/AppData/Local/Temp/RtmpINSOi7/file1c24761c798/FishStatsUtils_1.0.0.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
skipping pax global extended headers
3: In untar2(tarfile, files, list, exdir) :
skipping pax global extended headers
4: In untar2(tarfile, files, list, exdir) :
skipping pax global extended headers
5: In untar2(tarfile, files, list, exdir) :
skipping pax global extended headers
6: In untar2(tarfile, files, list, exdir) :
skipping pax global extended headers
7: In untar2(tarfile, files, list, exdir) :
skipping pax global extended headers
8: In untar2(tarfile, files, list, exdir) :
skipping pax global extended headers
### I also used R 3.5.2 in my computer. Although I have tried to install VAST and FishStatsUtils in several computers, none of them did not work.
Thank you!
