### ISSUE TITLE
Data_Fn names Options inconsistently with previous versions

### ISSUE THREAD

**Issue by cstawitz** [James-Thorson/VAST#144]
On `Data_Fn` lines 458 - 463, the list object is named `Options_List` for versions 5_5 and 6_0 instead of `Options_Vec` like in all other versions. 

This causes an issue in the `plot_anisotropy` function, since line 4 of `plot_anisotropy` calls `Options_vec`:
`if (TmbData$Options_vec["Aniso"] != 1) {`
but there is no object called `TmbData$Options_vec`

**Comment by James-Thorson** [comment]
Could you try reinstalling the latest FishStatsUtils and report back? I think I caught that one already

**Comment by cstawitz** [comment]
Yup it is fixed in the latest, though when I checked 4 days ago it was not fixed in the master branch
