### ISSUE TITLE
Param_Fn() error with v5_4_0

### ISSUE THREAD

**Issue by andrewdeines** [James-Thorson/VAST#148]
In line 108, the function is looking for "TmbData", instead of "DataList"

**Comment by James-Thorson** [comment]
Thanks, now fixed in main branch. I had caught that previously in the development branch, but am waiting longer for more testing prior to merging those new features

**Comment by andrewdeines** [comment]
Ditto in Make_Map()

**Comment by James-Thorson** [comment]
Thanks I appreciate the help.  Also feel free to use the development branch where these should already be sorted, devtools::install_github("james-thorson/VAST", ref="development")
