### ISSUE TITLE
 Bug in Make_Map

### ISSUE THREAD

**Issue by colemonnahan** [James-Thorson/VAST#150]
As of this commit:

https://github.com/James-Thorson/VAST/commit/51547591c8352d51e87aee1a492dc3d286259902#diff-2ea56af48bb1bee9101342763bab20cdL3

You took out the default for Q_config=TRUE but it is used later on in the code and thus throws an error that Q_config is not defined if Q_ik is used.

**Comment by James-Thorson** [comment]
Thanks, now fixed in development branch, and it didn't show up in master branch anyway
