### ISSUE TITLE
Remove detaching maps packages?

### ISSUE THREAD

**Issue by colemonnahan** [James-Thorson/VAST#152]
In several functions in VAST and FishStatsUtils you attach and then detach maps and maptools for each call. Why is this necessary? Can we remove this?  It's clunky and clutters up the workspace and shouldn't be necessary from what I can tell.

E.g.

https://github.com/James-Thorson/FishStatsUtils/blob/master/R/plot_maps.r#L57

**Comment by James-Thorson** [comment]
I don't want to attach it on loading the package, because I think there's some potential conflicts with other mapping options.  Also, my memory is that you can't call maps::map("worldHires") without loading maps and mapdata first.  

I'm open to specific ideas or proposals, particularly if you can show that it decreases clutter?

**Comment by colemonnahan** [comment]
Other packages you use within VAST and your other packages? Or do you mean some that users might have loaded for other purposes? If the former I can test that if you point me there? You're relying heavily on maps/maptools so I think it's ideal to have those loaded. They're also standard packages so if there's a namespace conflict you could do `foo::map` or whatever. Better to caveat that instead of an integral package. In my opinion.

It's particularly cluttered with multiple factors as functions get called in a loop over factors and then it occurs in multiple functions so I end up with something like the following. The informative messages get lost in there. A hack would be to suppress the package startup messages but that's... dangerous.

````
> Using L_pj for loadings matrix
Loading required package: maps

Attaching package: 'maps'

The following object is masked from 'package:plyr':

    ozone

Loading required package: mapdata
Using L_pj for loadings matrix
Loading required package: maps

Attaching package: 'maps'

The following object is masked from 'package:plyr':

    ozone

Loading required package: mapdata
Loading required package: maps

Attaching package: 'maps'

The following object is masked from 'package:plyr':

    ozone

Loading required package: mapdata
Using L_pj for loadings matrix
Loading required package: maps

Attaching package: 'maps'

The following object is masked from 'package:plyr':

    ozone

Loading required package: mapdata
Loading required package: maps

Attaching package: 'maps'

The following object is masked from 'package:plyr':

    ozone

Loading required package: mapdata
Loading required package: maps

Attaching package: 'maps'

The following object is masked from 'package:plyr':

    ozone

Loading required package: mapdata
Skipping plot of geometric anisotropy because it has been turned off
Loading required package: maps

Attaching package: 'maps'

The following object is masked from 'package:plyr':

    ozone

Loading required package: mapdata
````

**Comment by James-Thorson** [comment]
I'm aware of the annoying terminal printing ;)

If you load packages maps and mapdata in your own script, all plotting functions are designed to not do those terminal messages.  I will consider adding maps and mapdata to DEPENDS.

**Comment by colemonnahan** [comment]
It doesn't actually because in a few instances you don't wrap it in a conditional. So that detaches it and then for the rest of the functions it'll attach and detach it. So at a minimum please fix these:

https://github.com/James-Thorson/FishStatsUtils/blob/de3237fe4b1a7fb17fe229883a5e0642556ce877/R/plot_data.R#L22

https://github.com/James-Thorson/FishStatsUtils/blob/eb4b0b9109bcba59c2b8b9b187eaf23a2e176588/R/Geostat_Sim.R#L58

But I encourage depending directly on them which is more  clear to users. Many key functions won't work without them so to me VAST depends on these packages. This attach/detach is very unorthodox and could lead to some strange behavior, especially if someone had only one package (e.g., maps) loaded. 

What exact conflict are you worried about? I can dig into it if you want me to.

**Comment by James-Thorson** [comment]
I honestly can't remember about what conflicts there were.  Can you quickly determine if there are other analysis packages that add maps and mapdata to DEPENDS?

I'm close to convinced about adding them to DEPENDS, thanks for spending the time to discuss with me!

**Comment by colemonnahan** [comment]
You can see the reverse depends and suggests here:

https://cran.r-project.org/web/packages/maps/index.html
https://cran.r-project.org/web/packages/mapdata/index.html

They're standard packages. I don't envision a problem unless there's a namespace conflict with another package you want to use. We can drop it on the development branch and then see if any issues pop up during our testing.

**Comment by James-Thorson** [comment]
OK, just pushed to DEPENDS for FishStatsUtils, are you willing to try reinstalling that and VAST and confirm that it didn't do something obviously wrong?

**Comment by colemonnahan** [comment]
It now throws an error when you try to detach the package inside a function (e.g., plot_data). Can you remove those lines and I'll try again?

**Comment by colemonnahan** [comment]
Hi @James-Thorson I just forked the repo and fixed it in this pull request:

https://github.com/James-Thorson/FishStatsUtils/pull/6

So if you pull that in it should work.

**Comment by colemonnahan** [comment]
I tested this again with the development branch of VAST and everything is good. Thanks for updating that.
