### ISSUE TITLE
Scale of estimates and plot_maps function

### ISSUE THREAD

**Issue by mkajanus** [James-Thorson/VAST#158]
I want to plot fitted lines with the resulting predicted density estimates of VAST. I have extracted the values for log-predicted density from the "plot_maps" -function (plot set = 3). Similarly, I have extracted the values for my covariates using the same function (plot set = 11). I am now plotting the values and fitting a line for the plot using the resulting parameter estimations from the model.

I have two questions regarding the scale of the values.

Are the log-predicted density and covariate estimated values in the scale of the observations or in the scale of the linear-predictor (I have used gamma distribution)?

In" plot-maps" -function, there is option for "plot set" = 5 that is described on the help page as "Log-predicted density (rescaled)". How are the density estimates rescaled when using this setting and what is the resulting scale of the estimations?

Thank you for your help in advance.
Please let me know if there is more information I can provide you with.

Sincerely,
Mira

**Comment by James-Thorson** [comment]
Plot_set=5 is not super useful and please see plotting code for details.
Plot_set=3 is log density in kg per square km so not nexeassily either
scale, but links to data via area a_i

**Comment by mkajanus** [comment]
Thank you for your help.

Mira
