### ISSUE TITLE
output the density values of all points of plot_maps

### ISSUE THREAD

**Issue by T-zheng** [James-Thorson/VAST#159]
hi,
I got multi-species density surfaces for each year, but how can I output all density values(not the values of knots)?
Thanks

**Comment by T-zheng** [comment]
I want get all the species's density of extrapolation grids. But I just found the D_xcy ( density at each year、species and knot).

**Comment by James-Thorson** [comment]
using fine_scale=FALSE (as necessary in CPP <=7.0.0) the density at each extrapolation grid is equal to that at the nearest knot.  Please see `Spatial_List$NN_Extrap$nn.idx` for the vector associating each extrapolation grid-cell with each knot.

**Comment by T-zheng** [comment]
OK，Thank you very much！

**Comment by James-Thorson** [comment]
Also, feel free to email me directly if you want to access the `fine_scale=TRUE` features that can be used to interpolate density estimates at a finer spatial scale than the average distance between knots.
