### ISSUE TITLE
Bug in setting bounds in Lower/Upper for Beta_rho parameters

### ISSUE THREAD

**Issue by colemonnahan** [James-Thorson/VAST#160]
At some point you renamed Beta_rho1 to Beta_rho1_f and so this line of the code breaks:

https://github.com/James-Thorson/VAST/blob/development/R/make_model.R#L173

this means that Beta_rho1_f (and 2 of course) are unbounded and this slips through everything and, at least in tmbstan, will run with rho>1 without any warnings or complaints. I suggest putting in a check in `make_model` something like 

````
if(!all(Bounds[grep('rho', row.names(Bounds)),1]> -1))  stop("Invalid Rho bound")
````
And one for the upper too.

**Comment by James-Thorson** [comment]
Just pushed this change in the development branch, thanks!
