### ISSUE TITLE
Too many zeroes?

### ISSUE THREAD

**Issue by LibbyLogerwell** [James-Thorson/VAST#18]
I have a general question regarding delta models. Is there such a thing as too many zeroes? My ichthyoplankton catch data has 76% to 94% zeroes (depending on the taxa and year); the total number of stations is 140. I am wondering whether the positive catch rate part of a delta model would be informative for data that have as low as 6 non-zero observations. But perhaps a delta model would be useful for data that have 34 non-zero observations?

**Comment by James-Thorson** [comment]
Thanks @LibbyLogerwell for asking on the Issue Tracker, where others can also see the response ;)

There is no reason to think that a delta-model is inappropriate with a low number of positive catches, although it is not estimable when there is no encounters for any given year.  More importantly, it (or any other model) will become highly imprecise for predicting total abundance, center-of-distribution, etc. in any year with few encounters.  Given low-information data, its often advisable to "increase parsimony" (decrease number of estimated parameters).  For data with low positive catch rates, you could explore:

1.  using model selection to identify whether to include spatial and spatio-temporal terms for positive catch rates, i.e., setting some element of `FieldConfig` to `0`
2.  using a Poisson-process link function (approximating a Tweedie distribution) to induce a correlation between encounter probability and positive catch rates, and use this to predict low catch rates in areas with no encounters (using `ObsModel = c(2,1)`)

Finally, in my experience for low-positive-catch-rate species, the spatio-temporal model automatically estimates low SD for random effects, and a large decorrelation distance.  In these cases, the model is being "cautious" about inferring hotspots, as is probably appropriate given low-information species.
