### ISSUE TITLE
Function to output spatial abundance

### ISSUE THREAD

**Issue by pdolder** [James-Thorson/VAST#2]
Jim,

In addition to the functionality to produce maps, it would be good to be able to extract the spatial density estimates into a dataframe for external plotting.

Thanks,
Paul

**Comment by James-Thorson** [comment]
OK, I've partially addressed this request in two ways:

1.  I've added a new function `Summary( Obj )`, which will be expanded to
output a battery of useful and interpretable results, which are documented
using `?SpatialDeltaGLMM::Summary`.  Right now, it contains `D_xt` (density
at each knot and year), which I imagine is most important for plotting.

2.  I've changed `PlotResultsOnMap_Fn` to invisibly return the object that
it's plotting last for a given `plot_set` input (and have also added
documentation for what these mean).  So e.g.,

```R
PlotResultsOnMap_Fn( plot_set=c(3,10), ... )
```

will plot predicted log-density and the CV of density, but it will return
the CV of density in matrix form.

3.  I earlier added a new feature `plot_set=10` which plots the predicted
CV of density, which will only run if
`Data_Fn(...,Options=c('SD_site_logdensity'=1,...))`.

Jim

**Comment by pdolder** [comment]
Great, thanks! Will test and let you know any issues

**Comment by pdolder** [comment]
Jim,

Think (1) (Summarize not Summary ??) is not working correctly. Haven't tested on Obj, as I hadn't saved this from the run...but should this extract D_xct from the Report (which I had saved) not D_xt ?

**Comment by James-Thorson** [comment]
Sorry, I'll need more details here...

But yes, I changed it to `Summarize` (avoid namespace conflicts with base and utils).  And yes it currently only extracts `D_xct` (`Summarize` in the single species package `SpatialDeltaGLMM` extracts `D_xt`)

.. are you saying you get an error when using the function?

**Comment by pdolder** [comment]
No, sorry - I haven't an Obj to test it on at the moment (only saved Report, ParHat etc.. ) so haven't tested the function directly.  I had assumed the D_xct / D_xt issue was a typo....as it is not I've no doubt it will work fine.... will confirm
