### ISSUE TITLE
Check for and use the latest executable available 

### ISSUE THREAD

**Issue by John-R-Wallace** [James-Thorson/VAST#20]
The DESCRIPTION file has an old version listed:

Package: VAST
Type: Package
Title: Vector-autoregressive spatio-temporal (VAST) model
Version: 1.1.0
Date: 2016-08-09
Author: James Thorson
...

Using file.path() to obtain a path to a directory in a platform-independent way gives a viewable list:
 > list.files(R.home(file.path("library", "VAST", "executables")))
 [1] "VAST_v1_0_0.cpp"  "VAST_v1_1_0.cpp"  "VAST_v1_2_0.cpp"  "VAST_v1_3_0.cpp"  "VAST_v1_4_0.cpp"  "VAST_v1_5_0.cpp"  "VAST_v1_6_0.cpp"  "VAST_v1_7_0.cpp"  "VAST_v1_8_0.cpp" 
[10] "VAST_v1_9_0.cpp"  "VAST_v2_0_0.cpp"  "VAST_v2_1_0.cpp"  "VAST_v2_2_0.cpp" 

And until version 10_0_0 breaks it, the following can find the latest executable (if that is desired):
substr(list.files(R.home(file.path("library", "VAST", "executables")))[length(list.files(R.home(file.path("library", "VAST", "executables"))))], 1, 11)  
[1] "VAST_v2_2_0"

Hence:
Version <- substr(list.files(R.home(file.path("library", "VAST", "executables")))[length(list.files(R.home(file.path("library", "VAST", "executables"))))], 1, 11)  # Latest version up to v10_0_0 - then broken.

can be used until version 10_0_0 to always use the latest executable (for a given installation).

**Comment by James-Thorson** [comment]
I'm intentionally allowing people to specify the executable, so I don't chose to do this.
