### ISSUE TITLE
California_current region for the extrapolation grid contains the CCA

### ISSUE THREAD

**Issue by John-R-Wallace** [James-Thorson/VAST#21]
The California_current region for the extrapolation grid contains the CCA (Cowcod Conservation Area) where previously it did not.  The CCA is not trawled by the WCGBTS nor commercial fishers.

**Comment by James-Thorson** [comment]
Investigation shows that VAST is plotting densities for WCGBTS in all areas that were previously included in the design-based estimator, which seems like a reasonable default behavior.

**Comment by James-Thorson** [comment]
For WCGBTS plots, an alternative is to exclude plotting density in the Cowcod conservation area.  To do so, replace the line calling function `SpatialDeltaGLMM::MapDetails_Fn` with the following:

```R
MapDetails_List = SpatialDeltaGLMM::MapDetails_Fn( "Region"=Region, "NN_Extrap"=Spatial_List$PolygonList$NN_Extrap, "Extrapolation_List"=Extrapolation_List, "Include"=(Extrapolation_List[["Area_km2_x"]]>0 & ifelse(is.na(Extrapolation_List$Data_Extrap[,'Cowcod']),0,Extrapolation_List$Data_Extrap[,'Cowcod'])==0) )

```
