### ISSUE TITLE
time varying catchability 

### ISSUE THREAD

**Issue by N-DucharmeBarth** [James-Thorson/VAST#24]
Just a quick question on the catachability Q_ik. Would adding more columns in the "k" dimension allow for temporal variability in catchability?

**Comment by James-Thorson** [comment]
Yes, you could add (additional) columns to the catchability matrix Q_ik, and if some subset of those columns are a design-matrix for a factor (e.g., some grouping of years) then you can estimate changes in catchability among years.  If you take the interaction (product) of that design-matrix and your gear dummy-variable, then you get a time-varying pattern in catchability for a single gear.  However, you need to drop one column from each design-matrix to ensure that coefficients for Q_ik remain identifiable.  

I've also added an issue to add an identifiability check to function `Data_Fn` but I don't know when I'll get to it...
