### ISSUE TITLE
Coherence() returns error

### ISSUE THREAD

**Issue by pdolder** [James-Thorson/VAST#3]
Error in as.matrix(x) : object 'CovSum_hat' not found

Should it be derived within the function ?

**Comment by James-Thorson** [comment]
I'm conducting ongoing research regarding the statistical properties and ecological benefits of the statistics computed by `Coherence`, and haven't written it up yet.  You mind skipping this output for now?

**Comment by pdolder** [comment]
OK, understood - will close
