### ISSUE TITLE
VAST example for AFSC Triennial survey

### ISSUE THREAD

**Issue by gertsevv** [James-Thorson/VAST#31]
Jim,
Could you please provide an example to generate VAST index for AFSC triennial survey? Thanks a lot!

**Comment by James-Thorson** [comment]
I've added West Coast triennial data for yelloweye to `SpatialDeltaGLMM`, and an example script for analyzing it to `VAST` in the [examples directory](https://github.com/James-Thorson/VAST/blob/master/examples/West_Coast_Triennial_example_2017.R)
