### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by EllenY** [James-Thorson/VAST#33]
Hi,
In estimate fixed effects and predict random effects using this code I received an error message. 

Opt = TMBhelper::Optimize( obj=Obj, lower=TmbList[["Lower"]], upper=TmbList[["Upper"]], getsd=TRUE, savedir=DateFile, bias.correct=TRUE )

Error in sparseHessianFun(env, skipFixedEffects = skipFixedEffects) : 
  Memory allocation fail in function 'MakeADHessObject2'

Any thoughts on why I am getting this message?
Thank you

**Comment by James-Thorson** [comment]
This means you don't have enough memory on your machine to do bias-correction.  You have three easy options:

1.  Decrease number of knots `n_x` and re-run from beginning
2.  Turn off bias-correction, using `bias.correct=FALSE`
3.  Use a machine with more memory.
