### ISSUE TITLE
Lots of warnings about suggested cpp syntax

### ISSUE THREAD

**Issue by taylori** [James-Thorson/VAST#34]
The Build_TMB_Fn produces lots of warnings about suggested cpp syntax (first few out of 50+ warnings shown below). I still get reasonable output from running the model, but the warnings are distracting.

I'm using a 
- Windows 10, 
- VAST_v2_4_0, 
- R 3.3.3, 
- Rtools 3.4.0.1962, and 
- gcc version 4.9.3.

```
> TmbList <- VAST::Build_TMB_Fn("TmbData"=TmbData,
+     "RunDir"=DateFile,
+     "Version"=Version,
+     "RhoConfig"=RhoConfig,
+     "loc_x"=Spatial_List$loc_x,
+     "Method"=Method)
c:/Rtools/mingw_64/bin/g++  -I"c:/Users/ian.taylor/Documents/R/R-3.3.3/include" -DNDEBUG -Ic:/Users/IAN~1.TAY/DOCUME~1/R/R-33~1.3/library/TMB/include   -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_VAST_v2_4_0  -DTMB_LIB_INIT=R_init_VAST_v2_4_0    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c VAST_v2_4_0.cpp -o VAST_v2_4_0.o
VAST_v2_4_0.cpp: In instantiation of 'Type objective_function<Type>::operator()() [with Type = CppAD::AD<double>]':
c:/Users/IAN~1.TAY/DOCUME~1/R/R-33~1.3/library/TMB/include/tmb_core.hpp:1028:7:   required from here
VAST_v2_4_0.cpp:343:25: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
   if( Options_vec(7)==0 & Options_vec(0)==0 ){
                         ^
VAST_v2_4_0.cpp:347:25: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
   if( Options_vec(7)==0 & Options_vec(0)==1 ){
                         ^
VAST_v2_4_0.cpp:457:24: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
       if( t_iz(i,z)>=0 & t_iz(i,z)<n_t ){  // isNA doesn't seem to work for IMATRIX type
                        ^
VAST_v2_4_0.cpp:485:23: warning: suggest parentheses around comparison in operand of '|' [-Wparentheses]
...

```

**Comment by James-Thorson** [comment]
@taylori, are you willing to poke around to see how to disable these messages during compilation?

**Comment by taylori** [comment]
Warnings remain after updating to VAST_v4_4_0 and R 3.4.1 (other settings versions remain as noted in original post).

A bit of research leads me to see for 4 possible options for dealing with the warnings during the compiling step. So far, I've only figured out how to implement the first option.

1. Ignore the warnings (likely best if I'm the only one seeing them)
2. Add a `flags` or `...` input to `Build_TMB_Fn` that would be passed to the `flags` input in TMB's `compile` function that might allow the user to suppresses warnings based on commands here: https://gcc.gnu.org/onlinedocs/gcc-3.4.4/gcc/Warning-Options.html
3. Change my `Makevars` file (or some Windows equivalent), based on this comment by @kaskr: https://github.com/kaskr/adcomp/issues/169#issuecomment-182274629. But I'm not sure where this file would be located (in directory for R?, TMB?, VAST?)
4. Change the syntax of the VAST code being compiled so that these warnings aren't created. They all are related to the following categories [-Wparentheses], [-Wunused-variable], [-Wmaybe-uninitialized].

**Comment by James-Thorson** [comment]
Can you give specific advice how to do #2?

**Comment by kaskr** [comment]
@taylori
I see these warnings too. Better to fix the code - it's easy:

* All occurences like this
   `if( Options_vec(7)==0 & Options_vec(0)==0 ){`
   should be changed to
   `if( (Options_vec(7)==0) & (Options_vec(0)==0) ){`
* The `unused variable ‘n_k’ [-Wunused-variable]` is solved by removing `DATA_INTEGER(n_k);` as it is not needed.
* Same with
   ```
   VAST_v4_0_0.cpp:321:9: warning: unused variable ‘j’ [-Wunused-variable]
   int i,j,v,t,s,c,y,z;
   ```
   Most of these temporaries aren't needed. Change to
   `int i,t,c;`

**Comment by taylori** [comment]
Thanks @kaskr for your quick response. It certainly sounds more satisfying to fix the underlying cause of the warnings.
@James-Thorson, if you choose to go forward with the suggestion from @kaskr to fix the code (option 4 in my list), let me know if you want help. I'm can make a first attempt and create a pull request for these changes, but you would want to make sure to review the changes and do some testing to make sure nothing broke in the process. 

Also, I'm not sure what your workflow is for the VAST .cpp files. Would you change just the most recent, some range of files, or create a new file in the series? This shouldn't change any functionality, so probably just changing the most recent would be adequate.

**Comment by James-Thorson** [comment]
I try to avoid pushing changes back into earlier versions.  If you fork the
development branch and do a pull request after changing version
VAST_v4_1_0.cpp to eliminate the warnings, I'd be happy to merge that.

Thanks!
jim

**Comment by taylori** [comment]
All but 1 of the warnings go away after addition of changes suggested by @kaskr in commit 4334903. 
The remaining warning is
```
VAST_v4_1_0.cpp: In function 'tmbutils::matrix<Type> gmrf_by_category_nll(int, int, int, int, Type, tmbutils::array<Type>, tmbutils::array<Type>, tmbutils::vector<Type>, density::GMRF_t<scalartype>, Type&) [with Type = double]':
VAST_v4_1_0.cpp:126:71: warning: 'logtau' may be used uninitialized in this function [-Wmaybe-uninitialized]
     gmrf_sc = (gmrf_input_sf.matrix() * L_cf.transpose()) / exp(logtau);
                                                                       ^
```
It's easier to ignore 1 warning than 83, so I have no problem with it remaining, but it's also likely an easy fix for someone with more C++ experience.

Code seems to work fine though I didn't do a before/after comparison. Initial rows of index produced by single species example are as follows:
```
> pander::pandoc.table( Index$Table[,c("Year","Fleet","Estimate_metric_tons","SD_log","SD_mt")] ) 

--------------------------------------------------------
 Year   Fleet   Estimate_metric_tons   SD_log    SD_mt  
------ ------- ---------------------- --------- --------
 1982     1           2850224          0.08607   191971 

 1983     1           6748152          0.08629   447873 

```

Will now create a pull request.

**Comment by James-Thorson** [comment]
This is now fixed in the development branch using VAST_v4_1_0 and higher version numbers.
