### ISSUE TITLE
Update to: West_Coast_Annual_example_2017

### ISSUE THREAD

**Issue by John-R-Wallace** [James-Thorson/VAST#36]
The Data Warehouse changed their site so that now 'vessel' [changed to 'Vessel' by WCGBTS_Combo_Catch_Wt() ]  is given as a name not a number.  Thus, 
Data_Fn(...,  v_i = as.numeric(Data_Geostat[,'Vessel'])-1, ...)  needs to be changed to:
Data_Fn(..., v_i = Data_Geostat$Vessel, ...)

The updated file's permalink  is here: 
https://github.com/John-R-Wallace/VAST_Examples_and_Scripts/blob/7189a52ae8eef098308687364aa101069d3b950a/West_Coast_Annual_example_2017.R

I tested <v_i = Data_Geostat$Vessel> against <as.numeric(as.factor((Data_Geostat[,'Vessel']))-1> and both now give the same result

During the workshop 'vessel' only worked for myself and some others as:
< as.numeric(as.factor((Data_Geostat[,'Vessel']))-1> which starts an ordinal sequence at zero.  

I am unsure why Melissa had <as.numeric(Data_Geostat[,'Vessel'])-1> in her code.

**Comment by James-Thorson** [comment]
This will be resolved by moving the West Coast examples to a different project folder.
