### ISSUE TITLE
Plot_factors()

### ISSUE THREAD

**Issue by pdolder** [James-Thorson/VAST#4]
Getting a couple of errors....

1. FieldConfig not found  - this needs to be assigned within the function or read from Data$FieldConfig

2. Error in SpatialDFA::Rotate_Fn(Cov_jj = Cov_List[[paste0("Cov_", tolower(Par_name))]][,  : 
  Must provide either L_pj or Cov_jj

Possibly because the tolower in tolower(Par_name) is not compatible with how Par_name is defined.

Let me know if you'd prefer I fork, test and then push changes...

**Comment by James-Thorson** [comment]
Sorry, yes, I committed too early, and also noticed those bugs while trying with the "example--multispecies.R" script.  I'm working through them now and will email you when I think I've got them resolved

**Comment by pdolder** [comment]
No worries, happy to do testing

**Comment by pdolder** [comment]
Tested and working in the main....

Only thing needs fixing is the if(TmbData...) call in function -- The input to the function is just 'Data'

Thanks!
Paul
