### ISSUE TITLE
binned-poisson data

### ISSUE THREAD

**Issue by ceciliaOLearySBU** [James-Thorson/VAST#40]
After running the model with a few diff spp and altering model settings with the positive catch rate model set to 9 (binned-poisson), the encounter model observation model will no longer accept a logit-link with or without spatial & spatial-temporal turned on with error code:

 Some years and/or categories have either all or no encounters, and this is not permissible when ObsModel['Link']=0

Seems to be fixed when I alter the encounter model to a log-link. Is the way that the binned data is being fed into the encounter model also from 0 to 3 categories like the Poisson-binned abundance? 

Presence/absence info on spp tried:
Species 336: 15 years have 0, 5 years have presence
Species 239: 15 years have 0, 14 years have presence
Species 54: 13 years have 0, 15 years have presence

**Comment by James-Thorson** [comment]
You don't want to use a log-link for anything except a Tweedie or CPG density, so I should probably change it through an error for that if using `ObsModel = c(9,2)`.

If you have a year with 100% of tows not encountering a species, then the MLE for that year will be zero abundance.  You can avoid this sometimes by putting temporal structure on intercepts:

`RhoConfig[1]=1`

but this will sometimes still fail.  To test this, you can override the error-messages in `Data_Fn` by using `Data_Fn( ..., CheckForErrors=FALSE)`.

**Comment by ceciliaOLearySBU** [comment]
Thanks. What about for ObsModel = c(9,1) ? ObsModel[2] is also described as log-link for numbers-density and biomass.

**Comment by James-Thorson** [comment]
Hmm.  It doesn't really make sense to use `ObsModel[2]=1` for discrete-valued data.  I'm still trying to publish the paper describing the Poisson-link function used in that option, so write me if you want an advance copy.

**Comment by ceciliaOLearySBU** [comment]
Yea, agreed. That's why I was failing to understand why that's the only ObsModel[2] that will successfully complete fitting the model to the discrete data when some years have only absences. Will do!

**Comment by James-Thorson** [comment]
Yeah, I turned off the error message about encounter-probabilities for the Poisson-link model, because that link-function can deal better with years with 100% encounters than the conventional delta-model.
