### ISSUE TITLE
Data_Geostat

### ISSUE THREAD

**Issue by smartell** [James-Thorson/VAST#41]
There is an error in they example (https://github.com/James-Thorson/VAST/blob/master/examples/VAST--single-species_example.pdf) .  The object Data_Geostat has not been declared.  For 'cut & paster' R-folks, this bugs us.

**Comment by James-Thorson** [comment]
Sorry yes, I think it is in the Rmarkdown script but I dropped it from the
compiled PDF. I'll change that sometime soon.

**Comment by James-Thorson** [comment]
OK, I just committed a change in the formatting of the Rmarkdown code for the single-species example, and the compiled PDF that now includes the code for constructing `Data_Geostat`.  Easier to read?

**Comment by smartell** [comment]
Mahalo
