### ISSUE TITLE
Q about list of all fixed and random effects

### ISSUE THREAD

**Issue by gertsevv** [James-Thorson/VAST#42]
Hi Jim,

The SSC groundfish sub-committee chair requested to include a table in assessment reports that would list all the fixed and random effects used in VAST. What would the best way to get such a list?

Thank you.

**Comment by James-Thorson** [comment]
you first should re-install `ThorsonUtilities`:

```R
remove.packages("ThorsonUtilities")
devtools::install_github("James-Thorson/utilities")
```

you can then access a list of all fixed and random effects via:

```R
Table = ThorsonUtilities::list_parameters(Obj)
```

where `Obj` is the TMB object built for a given VAST model.  This will list all fixed and random effects, the number of coefficients for each, and what type they are (fixed or random).  To interpret the names of parameters, please read the equations in the user manual:  https://github.com/James-Thorson/VAST/blob/master/examples/VAST_user_manual.pdf.  I would also be happy to add a new function, say, `VAST::nwfsc_parameter_summary(Obj)`, which would run `ThorsonUtilities::list_parameters` and then format it in the specific way requested by the SSC.  However, I'm assuming the SSC hasn't yet requested a specific format, so I'm imagining this function will need to wait a bit until at least after a FRAM team meeting to discuss the topic.
