### ISSUE TITLE
undoing setwd() in Build_TMB_Fn?

### ISSUE THREAD

**Issue by DanOvando** [James-Thorson/VAST#49]
Build_TMB_Fn changes the working directory [here](https://github.com/James-Thorson/VAST/blob/69a9012ed50936c97750bdd55d314abae54f8a75/R/Build_TMB_Fn.R#L46), and leaves the working directory in this new location, resulting in users ending up in a different working directory than where they started after running the function. 

Is there a specific reason for this? If not, I would recommend doing something like 

```
CurrentDir = getwd()
setwd(RunDir)
```

and then adding in 
```
setwd(CurrentDir)
```
At the [end of the function](https://github.com/James-Thorson/VAST/blob/69a9012ed50936c97750bdd55d314abae54f8a75/R/Build_TMB_Fn.R#L150) so that the user's working directory is the same after running the function as it was before running.

**Comment by James-Thorson** [comment]
good advice.  TMB in early versions required the `setwd` during compilation or building on one of the major OSs (I forget which).  do you have linux, windows, and mac OSs to do some exploration of whether you can skip the `setwd` entirely and instead just specify the directory for the CPP file?

**Comment by DanOvando** [comment]
Ah gotcha, yeah I can poke around with that on my end

**Comment by James-Thorson** [comment]
This is now included.
