### ISSUE TITLE
TMB issue

### ISSUE THREAD

**Issue by EllenY** [James-Thorson/VAST#5]
Hi Jim,
I am getting an error when trying to run the VAST package multispecies example.

Do you think this might be a TMB installation or permission issue? 
# Make TMB object

TmbList = Build_TMB_Fn("TmbData"=TmbData, "RunDir"=DateFile, "Version"=Version, "RhoConfig"=RhoConfig, "loc_x"=Spatial_List$loc_x)

Error in compile(paste0(Version, ".cpp")) : Compilation failed
In addition: Warning message:
running command 'make -f "C:/PROGRA~1/R/R-33~1.1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" -f "C:\Users\ELLEN~1.YAS\AppData\Local\Temp\RtmpYtZ9IF\file2a30f7fbdd" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="VAST_v1_9_0.dll" WIN=64 TCLBIN=64 OBJECTS="VAST_v1_9_0.o"' had status 127 

I installed TMB with:      devtools::install_github("kaskr/adcomp/TMB") 

Many thanks,
Ellen

**Comment by James-Thorson** [comment]
yeah, status 127 is an install problem with TMB

**Comment by James-Thorson** [comment]
OK, I have done some new testing of the latest version of TMB, and it appears that it installs correctly through CRAN.  However, for Windows you have to install the version of Rtools that matches your version of R (here: https://cran.r-project.org/bin/windows/Rtools/)
