### ISSUE TITLE
Error in compile(paste0(Version, ".cpp")) : Compilation failed   +  Build_TMB_Fn?

### ISSUE THREAD

**Issue by Hanqingpeng** [James-Thorson/VAST#53]
When I run the following program: TmbList = Build_TMB_Fn(TmbData = TmbData, RunDir = DateFile, Version = Version, RhoConfig = RhoConfig, loc_x = Spatial_List$loc_x, Method = Method)

The following error occurred in the running results：
Note: Using Makevars in C:/Users/PC/Documents/.R/Makevars 
Error in compile(paste0(Version, ".cpp")) : Compilation failed

**Comment by James-Thorson** [comment]
What version of the CPP?

**Comment by Hanqingpeng** [comment]
VAST_v2_5_0.cpp

**Comment by James-Thorson** [comment]
What operating system? And is there an error message?

**Comment by Hanqingpeng** [comment]
windows7    R version 3.4.2   RStudio
There is an error message.
Note: Using Makevars in C:/Users/PC/Documents/.R/Makevars 
Error in compile(paste0(Version, ".cpp")) : Compilation failed
In addition: Warning message:
 Error in compile(paste0(Version, ".cpp")) : Compilation failed 

> Version
[1] "VAST_v2_5_0"
> VAST_v2_5_0
Error: object 'VAST_v2_5_0' not found
But VAST_v2_5_0.cpp file was found in the working directory

**Comment by James-Thorson** [comment]
Is this still an issue?  If not, please close the thread, and if yes please send along an update.

**Comment by andrewdeines** [comment]
I receive the same error when running the multispecies example, "VAST--multispecies_example.Rmd"
`> TmbList = Build_TMB_Fn("TmbData"=TmbData, "RunDir"=DateFile, "Version"=Version, "RhoConfig"=RhoConfig, "loc_x"=Spatial_List$loc_x, "Method"=Method)`
`Error in compile(paste0(Version, ".cpp")) : Compilation failed`
I've updated Version to 
`Version = "VAST_v2_8_0"#"VAST_v4_1_0"`

Windows 7, R v3.5.0

**Comment by James-Thorson** [comment]
Have you confirmed that TMB is successfully installed following instructions here:

https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/Steps-to-install-TMB

...?
