### ISSUE TITLE
X_xtp formatting help

### ISSUE THREAD

**Issue by areeder8** [James-Thorson/VAST#54]
I have been trying to look for some documentation on how to format X_xtp, does anyone know of something? Or can anyone give me help on how to formate this? I would like to be able to add a temperature, salinity, and depth to my analysis.  Those three covariates change for each data point. Thanks!

**Comment by James-Thorson** [comment]
Hi there, thanks for your interest.

Have you read through this:
https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/Adding-new-covariates
...?

Long story short: your can include a separate value for each observation
using a catchability covariate, but habitat covariates must be calculated
for each knot and time-interval.

**Comment by James-Thorson** [comment]
Please see new function `SpatialDeltaGLMM::format_covariates` that builds `X_xtp` from a user-defined data frame of covariate values
