### ISSUE TITLE
y_lim error on PlotIndex_Fn & Plot_range_shifts

### ISSUE THREAD

**Issue by hmorzaria** [James-Thorson/VAST#57]
I am having a hard time understanding where this error comes from. When running 

Index = SpatialDeltaGLMM::PlotIndex_Fn(DirName=this.path, TmbData=TmbData, Sdreport=Opt[["SD"]], Year_Set=Year$Year, Years2Include=Years2Include, use_biascorr=TRUE )
 
SpatialDeltaGLMM::Plot_range_shifts(Report=Report, TmbData=TmbData, Sdreport=Opt[["SD"]], Znames=colnames(TmbData$Z_xm), PlotDir=this.path, Year_Set=Year_Set)
 
I get 

Error in plot.window(...) : need finite 'ylim' values
In addition to a warning

Below is structure of the TmbData , followed by session info

> str(TmbData)
List of 35
 $ n_i                 : int 221
 $ n_s                 : int 237
 $ n_x                 : int 221
 $ n_t                 : num 12
 $ n_c                 : num 1
 $ n_j                 : int 1
 $ n_p                 : int 1
 $ n_k                 : int 1
 $ n_v                 : num 1
 $ n_l                 : int 1
 $ n_m                 : int 2
 $ Options_vec         : Named num [1:8] 1 0 0 0 0 200 1 0
  ..- attr(*, "names")= chr [1:8] "Aniso" "R2_interpretation" "Rho_betaTF" "Alpha" ...
 $ FieldConfig         : Named num [1:4] 1 1 1 1
  ..- attr(*, "names")= chr [1:4] "Omega1" "Epsilon1" "Omega2" "Epsilon2"
 $ OverdispersionConfig: Named num [1:2] -1 -1
  ..- attr(*, "names")= chr [1:2] "Vessel" "VesselYear"
 $ ObsModel            : num [1:2] 2 3
 $ Options             : Named num [1:9] 0 0 1 0 1 0 0 0 0
  ..- attr(*, "names")= chr [1:9] "SD_site_density" "SD_site_logdensity" "Calculate_Range" "Calculate_evenness" ...
 $ yearbounds_zz       : num [1, 1:2] 0 11
 $ b_i                 : num [1:221] 8.33 23.48 21.17 12 0 ...
 $ a_i                 : num [1:221] 1 1 1 1 1 1 1 1 1 1 ...
 $ c_i                 : num [1:221] 0 0 0 0 0 0 0 0 0 0 ...
 $ s_i                 : num [1:221] 0 1 2 3 4 5 6 7 8 9 ...
 $ t_iz                : int [1:221, 1] 0 0 0 0 0 0 0 0 1 1 ...
 $ v_i                 : num [1:221] 0 0 0 0 0 0 0 0 0 0 ...
 $ PredTF_i            : num [1:221] 0 0 0 0 0 0 0 0 0 0 ...
 $ a_xl                : num [1:221, 1] 52 40 20 4 36 4 36 28 4 16 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : NULL
  .. ..$ : chr "All_areas"
 $ X_xj                : num [1:221, 1] 0 0 0 0 0 0 0 0 0 0 ...
 $ X_xtp               : num [1:221, 1:12, 1] 0 0 0 0 0 0 0 0 0 0 ...
 $ Q_ik                : num [1:221, 1] 0 0 0 0 0 0 0 0 0 0 ...
 $ t_yz                : int [1:12, 1] 0 1 2 3 4 5 6 7 8 9 ...
 $ Z_xm                : num [1:221, 1:2] 524 525 530 537 539 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : NULL
  .. ..$ : chr [1:2] "E_km" "N_km"
 $ spde                :List of 3
  ..$ M0:Formal class 'dgTMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:237] 0 1 2 3 4 5 6 7 8 9 ...
  .. .. ..@ j       : int [1:237] 0 1 2 3 4 5 6 7 8 9 ...
  .. .. ..@ Dim     : int [1:2] 237 237
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : NULL
  .. .. .. ..$ : NULL
  .. .. ..@ x       : num [1:237] 88.34 111.16 59.16 3.11 115.34 ...
  .. .. ..@ factors : list()
  ..$ M1:Formal class 'dgTMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:1621] 0 1 18 74 86 105 106 0 1 72 ...
  .. .. ..@ j       : int [1:1621] 0 0 0 0 0 0 0 1 1 1 ...
  .. .. ..@ Dim     : int [1:2] 237 237
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : NULL
  .. .. .. ..$ : NULL
  .. .. ..@ x       : num [1:1621] 12.873 -3.225 -0.625 -0.833 -6.723 ...
  .. .. ..@ factors : list()
  ..$ M2:Formal class 'dgTMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:4981] 0 1 18 39 52 53 72 73 74 85 ...
  .. .. ..@ j       : int [1:4981] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..@ Dim     : int [1:2] 237 237
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : NULL
  .. .. .. ..$ : NULL
  .. .. ..@ x       : num [1:4981] 3.61 1.54 -1.12 1.69e+01 2.84e-07 ...
  .. .. ..@ factors : list()
 $ spde_aniso          :List of 9
  ..$ n_s     : int 237
  ..$ n_tri   : int 456
  ..$ Tri_Area: num [1:456] 18.19 211.96 1.46 15.03 18.78 ...
  ..$ E0      : num [1:456, 1:2] -8.222 30.891 -0.664 11.242 -4.54 ...
  ..$ E1      : num [1:456, 1:2] 3.78 -27.21 0.54 -11.76 -2.48 ...
  ..$ E2      : num [1:456, 1:2] 4.446 -3.682 0.124 0.521 7.016 ...
  ..$ TV      : num [1:456, 1:3] 30 7 68 85 52 46 231 44 90 39 ...
  ..$ G0      :Formal class 'dgTMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:237] 0 1 2 3 4 5 6 7 8 9 ...
  .. .. ..@ j       : int [1:237] 0 1 2 3 4 5 6 7 8 9 ...
  .. .. ..@ Dim     : int [1:2] 237 237
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : NULL
  .. .. .. ..$ : NULL
  .. .. ..@ x       : num [1:237] 88.34 111.16 59.16 3.11 115.34 ...
  .. .. ..@ factors : list()
  ..$ G0_inv  :Formal class 'dgTMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:237] 0 1 2 3 4 5 6 7 8 9 ...
  .. .. ..@ j       : int [1:237] 0 1 2 3 4 5 6 7 8 9 ...
  .. .. ..@ Dim     : int [1:2] 237 237
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : NULL
  .. .. .. ..$ : NULL
  .. .. ..@ x       : num [1:237] 0.01132 0.009 0.0169 0.32144 0.00867 ...
  .. .. ..@ factors : list()
 $ M0                  :Formal class 'dgTMatrix' [package "Matrix"] with 6 slots
  .. ..@ i       : int [1:491] 0 1 2 3 4 5 6 7 8 9 ...
  .. ..@ j       : int [1:491] 0 1 2 3 4 5 6 7 8 9 ...
  .. ..@ Dim     : int [1:2] 491 491
  .. ..@ Dimnames:List of 2
  .. .. ..$ : NULL
  .. .. ..$ : NULL
  .. ..@ x       : num [1:491] 1 1 1 1 1 1 1 1 1 1 ...
  .. ..@ factors : list()
 $ M1                  :Formal class 'dgTMatrix' [package "Matrix"] with 6 slots
  .. ..@ i       : int [1:1604] 1 4 0 5 3 6 2 7 0 5 ...
  .. ..@ j       : int [1:1604] 0 0 1 1 2 2 3 3 4 4 ...
  .. ..@ Dim     : int [1:2] 491 491
  .. ..@ Dimnames:List of 2
  .. .. ..$ : NULL
  .. .. ..$ : NULL
  .. ..@ x       : num [1:1604] 1 1 1 1 1 1 1 1 1 1 ...
  .. ..@ factors : list()
 $ M2                  :Formal class 'dgTMatrix' [package "Matrix"] with 6 slots
  .. ..@ i       : int [1:1480] 5 4 7 6 1 8 10 0 9 11 ...
  .. ..@ j       : int [1:1480] 0 1 2 3 4 4 4 5 5 5 ...
  .. ..@ Dim     : int [1:2] 491 491
  .. ..@ Dimnames:List of 2
  .. .. ..$ : NULL
  .. .. ..$ : NULL
  .. ..@ x       : num [1:1480] 1 1 1 1 1 1 1 1 1 1 ...
  .. ..@ factors : list()

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] broom_0.4.2            bindrcpp_0.2           pander_0.6.1           doSNOW_1.0.14         
 [5] snow_0.4-2             iterators_1.0.8        foreach_1.4.3          ThorsonUtilities_1.0  
 [9] TMB_1.7.11             VAST_1.5.0             SpatialDeltaGLMM_3.4.0 rmarkdown_1.6.0.9009  
[13] orthopolynom_1.0-5     polynom_1.3-9          splancs_2.01-40        arm_1.9-3             
[17] lme4_1.1-14            Matrix_1.2-10          MASS_7.3-47            rgdal_1.2-15          
[21] PBSmapping_2.70.4      maptools_0.9-2         sp_1.2-5               reshape_0.8.7         
[25] stringr_1.2.0          dplyr_0.7.4            purrr_0.2.4            readr_1.1.1           
[29] tidyr_0.7.2            tibble_1.3.4           tidyverse_1.1.1        scales_0.5.0.9000     
[33] devtools_1.13.3        RColorBrewer_1.1-2     ggmap_2.6.1            ggplot2_2.2.1.9000    
[37] ggthemes_3.4.0         magrittr_1.5           data.table_1.10.4     

loaded via a namespace (and not attached):
 [1] nlme_3.1-131      lubridate_1.6.0   httr_1.3.1        rprojroot_1.2     tools_3.4.0      
 [6] backports_1.1.0   R6_2.2.2.9000     lazyeval_0.2.0    colorspace_1.3-2  withr_2.1.0      
[11] tidyselect_0.2.2  mnormt_1.5-5      compiler_3.4.0    rvest_0.3.2       xml2_1.1.1       
[16] labeling_0.3      psych_1.7.5       digest_0.6.12     foreign_0.8-67    minqa_1.2.4      
[21] jpeg_0.1-8        pkgconfig_2.0.1   htmltools_0.3.6   maps_3.2.0        rlang_0.1.2      
[26] readxl_1.0.0      shape_1.4.3       bindr_0.1         jsonlite_1.5      TMBhelper_1.0    
[31] geosphere_1.5-5   Rcpp_0.12.13      munsell_0.4.3     abind_1.4-5       proto_1.0.0      
[36] stringi_1.1.5     plyr_1.8.4        grid_3.4.0        forcats_0.2.0     lattice_0.20-35  
[41] INLA_17.06.20     haven_1.0.0       splines_3.4.0     mapproj_1.2-5     hms_0.3          
[46] knitr_1.17        rjson_0.2.15      reshape2_1.4.2    codetools_0.2-15  glue_1.2.0       
[51] evaluate_0.10.1   mapdata_2.2-6     modelr_0.1.0      png_0.1-7         nloptr_1.0.4     
[56] RgoogleMaps_1.4.1 cellranger_1.1.0  RANN_2.5.1        gtable_0.2.0      assertthat_0.2.0 
[61] coda_0.19-1       memoise_1.1.0

**Comment by James-Thorson** [comment]
Do you see a file parameter_estimates.txt? If yes can you cut-paste it's
contents?

**Comment by hmorzaria** [comment]
$par
   ln_H_input    ln_H_input      beta1_ct      beta1_ct      beta1_ct      beta1_ct      beta1_ct 
 1.298670e+00  2.975554e+00  3.834670e-01  6.985509e-01  1.180277e+00 -2.148318e+00  1.842551e+00 
     beta1_ct      beta1_ct      beta1_ct      beta1_ct      beta1_ct      beta1_ct      beta1_ct 
-2.234569e+01  7.973473e-01 -2.067262e+01 -2.373595e+01 -6.873777e-01 -2.323236e+01 -2.334982e+01 
   L_omega1_z  L_epsilon1_z     logkappa1      beta2_ct      beta2_ct      beta2_ct      beta2_ct 
-1.761904e+00  2.401475e-06 -1.353980e+00  9.788438e-01  4.749883e+00  6.214591e+00  2.016866e+00 
     beta2_ct      beta2_ct      beta2_ct      beta2_ct      beta2_ct      beta2_ct      beta2_ct 
 6.086582e+00  8.479798e+00  5.167184e+00  8.479798e+00  8.479798e+00  2.472521e+00  8.479798e+00 
     beta2_ct    L_omega2_z  L_epsilon2_z     logkappa2     logSigmaM 
 8.479798e+00  3.319982e+00 -1.148342e+00 -2.370670e+00  2.001651e-01 

$objective
[1] 604.9385

$convergence
[1] 0

$iterations
[1] 1

$evaluations
function gradient 
       2        1 

$message
[1] "relative convergence (4)"

$run_time
Time difference of 27.84594 secs

$number_of_coefficients
 Total  Fixed Random 
  6195     33   6162 

$AIC
[1] 1275.877

$diagnostics
          Param starting_value      Lower           MLE     Upper final_gradient
1    ln_H_input      0.0000000 -50.000000  1.298670e+00 50.000000   2.549746e-06
2    ln_H_input      0.0000000 -50.000000  2.975554e+00 50.000000   7.054100e-07
3      beta1_ct     -5.7761810 -50.000000  3.834670e-01 50.000000   4.795324e-06
4      beta1_ct     -5.7761810 -50.000000  6.985509e-01 50.000000  -5.197590e-06
5      beta1_ct     -5.7761810 -50.000000  1.180277e+00 50.000000   2.912496e-06
6      beta1_ct     -5.7761810 -50.000000 -2.148318e+00 50.000000  -1.403486e-05
7      beta1_ct     -5.7761810 -50.000000  1.842551e+00 50.000000   9.541677e-06
8      beta1_ct     -5.7761810 -50.000000 -2.234569e+01 50.000000   6.191990e-09
9      beta1_ct     -5.7761810 -50.000000  7.973473e-01 50.000000  -2.150560e-05
10     beta1_ct     -5.7761810 -50.000000 -2.067262e+01 50.000000   5.174388e-08
11     beta1_ct     -5.7761810 -50.000000 -2.373595e+01 50.000000   2.143144e-09
12     beta1_ct     -5.7761810 -50.000000 -6.873777e-01 50.000000  -9.138371e-06
13     beta1_ct     -5.7761810 -50.000000 -2.323236e+01 50.000000   2.114367e-09
14     beta1_ct     -5.7761810 -50.000000 -2.334982e+01 50.000000   1.595905e-09
15   L_omega1_z     -1.9018252 -50.000000 -1.761904e+00 50.000000   4.089589e-06
16 L_epsilon1_z      0.5245683 -50.000000  2.401475e-06 50.000000   1.886454e-07
17    logkappa1     -0.1053605  -4.521507 -1.353980e+00  3.765938  -8.069244e-06
18     beta2_ct      8.4797977 -50.000000  9.788438e-01 50.000000  -2.007422e-06
19     beta2_ct      8.4797977 -50.000000  4.749883e+00 50.000000   5.432679e-06
20     beta2_ct      8.4797977 -50.000000  6.214591e+00 50.000000  -3.125752e-06
21     beta2_ct      8.4797977 -50.000000  2.016866e+00 50.000000  -1.664350e-06
22     beta2_ct      8.4797977 -50.000000  6.086582e+00 50.000000  -1.758472e-06
23     beta2_ct      8.4797977 -50.000000  8.479798e+00 50.000000   0.000000e+00
24     beta2_ct      8.4797977 -50.000000  5.167184e+00 50.000000  -7.249992e-07
25     beta2_ct      8.4797977 -50.000000  8.479798e+00 50.000000   0.000000e+00
26     beta2_ct      8.4797977 -50.000000  8.479798e+00 50.000000   0.000000e+00
27     beta2_ct      8.4797977 -50.000000  2.472521e+00 50.000000   9.375202e-06
28     beta2_ct      8.4797977 -50.000000  8.479798e+00 50.000000   0.000000e+00
29     beta2_ct      8.4797977 -50.000000  8.479798e+00 50.000000   0.000000e+00
30   L_omega2_z      2.3531280 -50.000000  3.319982e+00 50.000000   2.759502e-06
31 L_epsilon2_z     -1.3959831 -50.000000 -1.148342e+00 50.000000  -1.058569e-05
32    logkappa2     -0.1053605  -4.521507 -2.370670e+00  3.765938  -3.660941e-05
33    logSigmaM      1.6094379 -50.000000  2.001651e-01 10.000000  -1.967866e-06

$SD
sdreport(.) result
                  Estimate Std. Error
ln_H_input    1.298670e+00        NaN
ln_H_input    2.975554e+00        NaN
beta1_ct      3.834670e-01        NaN
beta1_ct      6.985509e-01        NaN
beta1_ct      1.180277e+00        NaN
beta1_ct     -2.148318e+00        NaN
beta1_ct      1.842551e+00        NaN
beta1_ct     -2.234569e+01        NaN
beta1_ct      7.973473e-01        NaN
beta1_ct     -2.067262e+01        NaN
beta1_ct     -2.373595e+01        NaN
beta1_ct     -6.873777e-01        NaN
beta1_ct     -2.323236e+01        NaN
beta1_ct     -2.334982e+01        NaN
L_omega1_z   -1.761904e+00        NaN
L_epsilon1_z  2.401475e-06        NaN
logkappa1    -1.353980e+00        NaN
beta2_ct      9.788438e-01        NaN
beta2_ct      4.749883e+00        NaN
beta2_ct      6.214591e+00        NaN
beta2_ct      2.016866e+00        NaN
beta2_ct      6.086582e+00        NaN
beta2_ct      8.479798e+00        NaN
beta2_ct      5.167184e+00        NaN
beta2_ct      8.479798e+00        NaN
beta2_ct      8.479798e+00        NaN
beta2_ct      2.472521e+00        NaN
beta2_ct      8.479798e+00        NaN
beta2_ct      8.479798e+00        NaN
L_omega2_z    3.319982e+00        NaN
L_epsilon2_z -1.148342e+00        NaN
logkappa2    -2.370670e+00        NaN
logSigmaM     2.001651e-01        NaN
Warning:
Hessian of fixed effects was not positive definite.
Maximum gradient component: 3.660941e-05

**Comment by James-Thorson** [comment]
Turn of spatiotemporal variance for component #1 and it should work, or
repost the problem after trying?

**Comment by hmorzaria** [comment]
Same error with 
FieldConfig = c(Omega1 = 1, Epsilon1 = 0, Omega2 = 1,
                  Epsilon2 = 1)

**Comment by James-Thorson** [comment]
Can you send parameter_eatimatea again?

**Comment by hmorzaria** [comment]
$par
  ln_H_input   ln_H_input     beta1_ct     beta1_ct     beta1_ct     beta1_ct     beta1_ct     beta1_ct     beta1_ct 
  -1.8158782    8.2204141    0.5654332    0.8659052    1.0942973   -1.9097119    2.1962389  -39.4497989    0.9057073 
    beta1_ct     beta1_ct     beta1_ct     beta1_ct     beta1_ct   L_omega1_z    logkappa1     beta2_ct     beta2_ct 
 -45.2607373  -45.5019745   -0.6195804  -45.5607960  -50.0000000   20.2471722    3.2767828    2.7992969    6.1526418 
    beta2_ct     beta2_ct     beta2_ct     beta2_ct     beta2_ct     beta2_ct     beta2_ct     beta2_ct     beta2_ct 
   6.9530054    3.1110387    7.8899478    8.4797977    6.0764458    8.4797977    8.4797977    3.8380518    8.4797977 
    beta2_ct   L_omega2_z L_epsilon2_z    logkappa2    logSigmaM 
   8.4797977   18.3568939   -7.4895223    1.1797523    0.2296554 

$objective
[1] 605.0831

$convergence
[1] 0

$iterations
[1] 1

$evaluations
function gradient 
       2        1 

$message
[1] "relative convergence (4)"

$run_time
Time difference of 32.20976 secs

$number_of_coefficients
 Total  Fixed Random 
  3350     32   3318 

$AIC
[1] 1274.166

$diagnostics
          Param starting_value      Lower         MLE     Upper final_gradient
1    ln_H_input      0.0000000 -50.000000  -1.8158782 50.000000  -1.549275e-05
2    ln_H_input      0.0000000 -50.000000   8.2204141 50.000000  -7.049083e-06
3      beta1_ct     -5.7761810 -50.000000   0.5654332 50.000000   4.341197e-08
4      beta1_ct     -5.7761810 -50.000000   0.8659052 50.000000  -1.819329e-07
5      beta1_ct     -5.7761810 -50.000000   1.0942973 50.000000   1.473671e-06
6      beta1_ct     -5.7761810 -50.000000  -1.9097119 50.000000  -5.560477e-06
7      beta1_ct     -5.7761810 -50.000000   2.1962389 50.000000  -3.521787e-07
8      beta1_ct     -5.7761810 -50.000000 -39.4497989 50.000000   2.193820e-16
9      beta1_ct     -5.7761810 -50.000000   0.9057073 50.000000   1.449304e-06
10     beta1_ct     -5.7761810 -50.000000 -45.2607373 50.000000   9.244646e-19
11     beta1_ct     -5.7761810 -50.000000 -45.5019745 50.000000   4.698743e-19
12     beta1_ct     -5.7761810 -50.000000  -0.6195804 50.000000   1.829374e-06
13     beta1_ct     -5.7761810 -50.000000 -45.5607960 50.000000   4.703975e-19
14     beta1_ct     -5.7761810 -50.000000 -50.0000000 50.000000   3.443488e-21
15   L_omega1_z      0.2813971 -50.000000  20.2471722 50.000000  -2.594589e-06
16    logkappa1     -0.1053605  -4.521507   3.2767828  3.765938   5.939409e-06
17     beta2_ct      8.4797977 -50.000000   2.7992969 50.000000   2.019318e-06
18     beta2_ct      8.4797977 -50.000000   6.1526418 50.000000  -9.526990e-07
19     beta2_ct      8.4797977 -50.000000   6.9530054 50.000000  -3.100277e-06
20     beta2_ct      8.4797977 -50.000000   3.1110387 50.000000   2.201156e-06
21     beta2_ct      8.4797977 -50.000000   7.8899478 50.000000  -1.800160e-06
22     beta2_ct      8.4797977 -50.000000   8.4797977 50.000000   0.000000e+00
23     beta2_ct      8.4797977 -50.000000   6.0764458 50.000000   1.067274e-06
24     beta2_ct      8.4797977 -50.000000   8.4797977 50.000000   0.000000e+00
25     beta2_ct      8.4797977 -50.000000   8.4797977 50.000000   0.000000e+00
26     beta2_ct      8.4797977 -50.000000   3.8380518 50.000000  -1.133803e-06
27     beta2_ct      8.4797977 -50.000000   8.4797977 50.000000   0.000000e+00
28     beta2_ct      8.4797977 -50.000000   8.4797977 50.000000   0.000000e+00
29   L_omega2_z      0.3011176 -50.000000  18.3568939 50.000000  -5.394980e-06
30 L_epsilon2_z     -0.9449430 -50.000000  -7.4895223 50.000000   5.263664e-06
31    logkappa2     -0.1053605  -4.521507   1.1797523  3.765938   1.139700e-05
32    logSigmaM      1.6094379 -50.000000   0.2296554 10.000000  -1.530908e-05

$SD
sdreport(.) result
                Estimate Std. Error
ln_H_input    -1.8158782        NaN
ln_H_input     8.2204141        NaN
beta1_ct       0.5654332        NaN
beta1_ct       0.8659052        NaN
beta1_ct       1.0942973        NaN
beta1_ct      -1.9097119        NaN
beta1_ct       2.1962389        NaN
beta1_ct     -39.4497989        NaN
beta1_ct       0.9057073        NaN
beta1_ct     -45.2607373        NaN
beta1_ct     -45.5019745        NaN
beta1_ct      -0.6195804        NaN
beta1_ct     -45.5607960        NaN
beta1_ct     -50.0000000        NaN
L_omega1_z    20.2471722        NaN
logkappa1      3.2767828        NaN
beta2_ct       2.7992969        NaN
beta2_ct       6.1526418        NaN
beta2_ct       6.9530054        NaN
beta2_ct       3.1110387        NaN
beta2_ct       7.8899478        NaN
beta2_ct       8.4797977        NaN
beta2_ct       6.0764458        NaN
beta2_ct       8.4797977        NaN
beta2_ct       8.4797977        NaN
beta2_ct       3.8380518        NaN
beta2_ct       8.4797977        NaN
beta2_ct       8.4797977        NaN
L_omega2_z    18.3568939        NaN
L_epsilon2_z  -7.4895223        NaN
logkappa2      1.1797523        NaN
logSigmaM      0.2296554        NaN
Warning:
Hessian of fixed effects was not positive definite.
Maximum gradient component: 1.549275e-05

**Comment by James-Thorson** [comment]
It looks like years 6, 8, 9, 11, and 12 have the beta1 going to -Inf (i.e.,
< -20), and their gradients are going to zero, the hessian is not
invertable, and the SEs are all NaNs.  The model is therefore not
converged.  I recommend determining why this is occurring.

Jim

**Comment by hmorzaria** [comment]
That occurs because no data was collected for that species in those years. 
Sorry, my error. I initially thought the plot.window error had to do with a problem with graphics (I am running on a headless Linux server and had a hard time installing INLA). Separately, I assumed VAST would automatically account for data as 0 for a specific time period. I will remove the data a priori.
Thanks for your help.
