### ISSUE TITLE
Question for the "Optimize" function in TMBhelper

### ISSUE THREAD

**Issue by sea521** [James-Thorson/VAST#59]
I am using VAST to estimate a single species abundance in the Yellow Sea, China. The model converged with no fixed parameters hitting the bounds, if I set the "newtonsteps" equal 0 in the "Optimize" function of TMBhelper. Otherwise, the model didn't converge with the final gradients for most fixed parameters not close to 0, if the "newtonsteps" equals 1. What does this mean?

The anisotropy parameters are looking strange (extreme values and high CVs). 

>                   Estimate   Std. Error
> ln_H_input    4.0958493986 3.800424e+01
> ln_H_input   46.0199291114 1.749246e+03
> 
> 

So, I turned Aniso=FALSE in Data_Fn and repeated the process as suggested by Dr. Thorson. Now, the model converged with newtonsteps = 1 in Optimize. Many thanks to Dr. Thorson. :-)

**Comment by James-Thorson** [comment]
Great! Glad to hear, and happy to keep discussing.

If you end up describing results in a public document, do you mind listing
it on the wiki:

https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/Stock-assessments-using-SpatialDeltaGLMM

...?

**Comment by sea521** [comment]
Of course, I don't mind. I will tell you when I finish the work. Then, please list it on the wiki. Thank you.
