### ISSUE TITLE
ThorsonUtilities package also needs to be installed 

### ISSUE THREAD

**Issue by jin-gao** [James-Thorson/VAST#6]
devtools::install_github("James-Thorson/utilities")

**Comment by taylori** [comment]
The devtools::install_github function has had some issues with package dependencies. Folks working on the ss3sim package found that updating devtools first fixed the issue and didn't require additional packages to be manually installed. See https://github.com/ss3sim/ss3sim/issues/235 for more information. I'm not sure if this is the case with VAST or not.

**Comment by James-Thorson** [comment]
Jin,  I'll need more details to understand your suggestion.  `ThorsonUtilities` is already installed in the `.onAttach` function in zzz.R

**Comment by jin-gao** [comment]
I had to install ThorsonUtilities separately otherwise I get "convert_to_unicode" is not an exported object from 'namespace'  ThorsonUtilities.

**Comment by James-Thorson** [comment]
You had an old version of ThorsonUtilities installed, so it prevented it from re-installing except manually.  I'll take this as a vote in favor of forcing re-install of dependencies (using `force=TRUE`) but won't do this unless I get at least one other reported bug caused by this
