### ISSUE TITLE
How to include measured categorical variables affecting catch rates?

### ISSUE THREAD

**Issue by sea521** [James-Thorson/VAST#60]
Dr. Thorson,

I am using VAST for a single species with diel vertical movement. I wonder how I can include the effects of different diurnal periods on catchability to explain variation in density. Diurnal period is a categorical variable. Should I include measured diurnal periods in "v_i" and set OverdispersionConfig = c("Delta1"=1, "Delta2"=1), or in "Q_ik"? Any suggestion? Thank you.

**Comment by James-Thorson** [comment]
A few thoughts:

* Yes, you could include diurnal period as a categorical variable in `Q_ik`.  To do so, e.g., try converting to a design-matrix using `ThorsonUtilities::vector_to_design_matrix`, and then dropping one column to ensure that catchability differences are not confounded with year effects.
* No, `OverdispersionConfig` is not necessary for this, and in fact is used differently (it controls the use of data input `v_i`)
* If I were you, I would try using a cyclic smooth function:
```R
Q_ik = NULL
Q_ik[,1] = cos( d / 24 )
Q_ik[,2] = sin( d / 24 )
```

where d is the daily timing in hours.minutes, where minutes is in decimal hours.
