### ISSUE TITLE
Error in RANN::nn2(data = loc_grid, query = loc_i, k = 1) :    Query and data tables must have same dimensions

### ISSUE THREAD

**Issue by Thom-Teears** [James-Thorson/VAST#64]
Dr. Thorson,
      I am having trouble running the single-species example you have provided. Do you have any suggestions on how to fix the following error?

       Error in RANN::nn2(data = loc_grid, query = loc_i, k = 1) :    Query and data tables must have same dimensions

      My OS is Windows 10 Education and I do have install privileges.

Many thanks,
Thom

**Comment by James-Thorson** [comment]
Please remove packages `SpatialDeltaGLMM` and `VAST`, and then re-install `VAST`.  If that works, please close the issue, otherwise please respond.

**Comment by Thom-Teears** [comment]
Dr. Thorson,
     Your suggestion solved this error. 

Many thanks,
Thom

**Comment by Thom-Teears** [comment]
Thanks for your help. I really appreciate it.
