### ISSUE TITLE
Using Prepare_User_Extrapolation_Data_Fn.R

### ISSUE THREAD

**Issue by agruss2** [James-Thorson/VAST#65]
@James-Thorson  I am currently trying to use VAST to estimate CPUE indices for fish populations of the North Atlantic. 
Since the North Atlantic does not belong to the list of "Regions", I can only rely on "Prepare_Other_Extrapolation_Data_Fn.R" or "Prepare_User_Extrapolation_Data_Fn.R" to generate my extrapolation list. 
I do not wish to rely on "Prepare_Other_Extrapolation_Data_Fn.R", so as to save some computational time. 
However, when I indicate that my region is "User", VAST picks "Prepare_Other_Extrapolation_Data_Fn.R" instead of "Prepare_User_Extrapolation_Data_Fn.R" and, therefore, asks me to provide "observations_LL" input.
Here is what I would like to implement, please:
> if( Region %in% c("User") ){
>   north_atlantic_grid = read.csv( "Lattice_North_Atlantic.csv" )
>   Extrapolation_List = SpatialDeltaGLMM::Prepare_Extrapolation_Data_Fn( Region=Region, 
>     strata.limits=strata.limits, input_grid=north_atlantic_grid ) 
> }

The version I am using is "VAST_v2_5_0"
Could you please tell me how we could solve this issue? 
Many thanks!

**Comment by James-Thorson** [comment]
Hmm.  This is strange.  If you type:

```R
SpatialDeltaGLMM::Prepare_Extrapolation_Data_Fn
```

You should see

```R
> SpatialDeltaGLMM::Prepare_Extrapolation_Data_Fn
function (Region, strata.limits, observations_LL = NULL, input_grid = NULL, 
    ...) 
{
    Extrapolation_List = NULL
    if (tolower(Region) == "california_current") {
        Extrapolation_List = SpatialDeltaGLMM::Prepare_WCGBTS_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            ...)
    }
    if (tolower(Region) %in% c("wcghl", "wcghl_domain")) {
        Extrapolation_List = SpatialDeltaGLMM::Prepare_WCGHL_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            ...)
    }
    if (tolower(Region) == "british_columbia") {
        Extrapolation_List = SpatialDeltaGLMM::Prepare_BC_Coast_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            ...)
    }
    if (tolower(Region) == "eastern_bering_sea") {
        Extrapolation_List = SpatialDeltaGLMM::Prepare_EBS_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            ...)
    }
    if (tolower(Region) == "aleutian_islands") {
        Extrapolation_List = SpatialDeltaGLMM::Prepare_AI_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            ...)
    }
    if (tolower(Region) == "gulf_of_alaska") {
        Extrapolation_List = SpatialDeltaGLMM::Prepare_GOA_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            ...)
    }
    if (tolower(Region) == "northwest_atlantic") {
        Extrapolation_List = SpatialDeltaGLMM::Prepare_NWA_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            ...)
    }
    if (tolower(Region) == "south_africa") {
        Extrapolation_List = SpatialDeltaGLMM::Prepare_SA_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            ...)
    }
    if (tolower(Region) == "gulf_of_st_lawrence") {
        Extrapolation_List = SpatialDeltaGLMM::Prepare_GSL_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            ...)
    }
    if (tolower(Region) == "new_zealand") {
        Extrapolation_List = SpatialDeltaGLMM::Prepare_NZ_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            ...)
    }
    if (tolower(Region) == "habcam") {
        Extrapolation_List = SpatialDeltaGLMM::Prepare_HabCam_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            ...)
    }
    if (tolower(Region) == "gulf_of_mexico") {
        Extrapolation_List = SpatialDeltaGLMM::Prepare_GOM_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            ...)
    }
    if (tolower(Region) == "user") {
        if (is.null(input_grid)) 
            message("Because you're using a user-supplied region, please provide 'input_grid' input")
        if (!(all(c("Lat", "Lon", "Area_km2") %in% colnames(input_grid)))) 
            message("'input_grid' must contain columns named 'Lat', 'Lon', and 'Area_km2'")
        Extrapolation_List = SpatialDeltaGLMM::Prepare_User_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            input_grid = input_grid, ...)
    }
    if (is.null(Extrapolation_List)) {
        if (is.null(observations_LL)) 
            message("Because you're using a new region, please provide 'observations_LL' input")
        Extrapolation_List = SpatialDeltaGLMM::Prepare_Other_Extrapolation_Data_Fn(strata.limits = strata.limits, 
            observations_LL = observations_LL, ...)
    }
    return(Extrapolation_List)
}
<environment: namespace:SpatialDeltaGLMM>
```

which shows that `Region="User"` should trigger using `SpatialDeltaGLMM::Prepare_User_Extrapolation_Data_Fn`.  Do you not see this?  Or can you try and do some sleuthing to figure out why that's not showing up for you?  

If you can't solve it, please email me a minimal reproducible example (https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/How-to-create-a-minimal-example)

**Comment by agruss2** [comment]
@James-Thorson 
When I type this:

> SpatialDeltaGLMM::Prepare_Extrapolation_Data_Fn

I get this: 

> function (Region, strata.limits, observations_LL = NULL, ...) 
> {
>     Extrapolation_List = NULL
>     if (tolower(Region) == "california_current") {
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_WCGBTS_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             ...)
>     }
>     if (tolower(Region) %in% c("wcghl", "wcghl_domain")) {
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_WCGHL_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             ...)
>     }
>     if (tolower(Region) == "british_columbia") {
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_BC_Coast_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             ...)
>     }
>     if (tolower(Region) == "eastern_bering_sea") {
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_EBS_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             ...)
>     }
>     if (tolower(Region) == "aleutian_islands") {
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_AI_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             ...)
>     }
>     if (tolower(Region) == "gulf_of_alaska") {
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_GOA_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             ...)
>     }
>     if (tolower(Region) == "northwest_atlantic") {
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_NWA_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             ...)
>     }
>     if (tolower(Region) == "south_africa") {
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_SA_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             ...)
>     }
>     if (tolower(Region) == "gulf_of_st_lawrence") {
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_GSL_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             ...)
>     }
>     if (tolower(Region) == "new_zealand") {
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_NZ_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             ...)
>     }
>     if (tolower(Region) == "habcam") {
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_HabCam_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             ...)
>     }
>     if (tolower(Region) == "gulf_of_mexico") {
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_GOM_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             ...)
>     }
>     if (is.null(Extrapolation_List)) {
>         if (is.null(observations_LL)) 
>             message("Because you're using a new region, please provide 'observations_LL' input")
>         Extrapolation_List = SpatialDeltaGLMM:::Prepare_Other_Extrapolation_Data_Fn(strata.limits = strata.limits, 
>             observations_LL = observations_LL, ...)
>     }
>     return(Extrapolation_List)
> }
> <environment: namespace:SpatialDeltaGLMM>

I guess that this is because "Prepare_User_Extrapolation_Data_Fn.R" was created two months ago and, for some reason, the latest code of VAST is not downloaded in my laptop when I run VAST. 
Does this have to do with the Version of VAST I am using? If so, which Version should I use? 
Many thanks!

**Comment by James-Thorson** [comment]
Please delete both VAST and SpatialDeltaGLMM, and reinstall VAST. Tell me
if that doesn't work, or close the issue if it does.

**Comment by agruss2** [comment]
@James-Thorson Yes, indeed, when I did some sleuthing earlier I deleted VAST before re-running the script but not SpatialDeltaGLMM! Shame on me. Now that I deleted both VAST and SpatialDeltaGLMM before re-running the script, it's working. I'll keep you posted about progress on the CPUE project. 
Many thanks Jim!
