### ISSUE TITLE
Installing the package "pander" only if not already installed 

### ISSUE THREAD

**Issue by agruss2** [James-Thorson/VAST#66]
@James-Thorson (This is a very minor issue!). 
To make the life of the user easier, it would be good to have VAST install the package "pander" only if not already installed. 
For example, in "VAST--single-species_example.Rmd", I would suggest replacing (l. 22):

> install.packages(new.packages, repos="http://cran.us.r-project.org")

with:

> list.of.packages <- c("pander")
> new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
> if(length(new.packages)) install.packages(new.packages, repos="http://cran.us.r-project.org")

Many thanks!

**Comment by James-Thorson** [comment]
Arnaud,
Thanks for the useful feedback.  However, I envision that users can modify the tutorial Rmarkdown scripts to change things like this if running it repeatedly, and their main point is to show new user how to apply the model as simply as possible.  You're suggested change would make the code more difficult to read, and therefore seems more harmful than helpful.  I therefore decline on this suggestion.
PS:  I'll respond to your other query tomorrow!
