### ISSUE TITLE
Requirement for Prop_nonzero != 0 | 1 when using TFpred

### ISSUE THREAD

**Issue by pdolder** [James-Thorson/VAST#7]
The error below comes up when predicting using TFpred = 1. This stops you using NAs in response variable when predicting.

"stop("Some years and/or categories have either all or no encounters, and this is not permissible when ObsModel['Link']=0")"

As a workaround, you can fill the response variable with some random numbers, but might be easier to exclude from the check.

**Comment by James-Thorson** [comment]
So why would you include an NA in your predictive set of data, i.e, have an observation `b_i[i]=NA` and `PredTF[i]=1` for any `i`?

The intent of this option is to calculate the predictive probability of some leave-out-data (using Empirical Bayes predictions), so I can only imagine using it when b_i is some real, observed data for the predictive set.

**Comment by pdolder** [comment]
Okay, I'd clearly gotten the wrong end of the stick....

I was looking at one step ahead predictions (i.e. a spatial density forecast at t+1) but that is not what this is about

**Comment by James-Thorson** [comment]
Ah! And you have data for the next year that you want to use to test fit (like timeseries leave one out) or its a pure forecast without testing data?

The former it's makes sense to use PredTF. The latter is better done other ways I think

**Comment by pdolder** [comment]
Yes, that's it - I have the testing data, but I get your meaning now to just set TFpred=1 and it will be left out of the fit. Then there are diagnostics as to the predicted v the observed in the report ?

**Comment by James-Thorson** [comment]
Yeah there's a pred_jnll for predictive joint negloglike

**Comment by pdolder** [comment]
Great, cheers
