### ISSUE TITLE
ObsModel Guidance for 100% encounter rates

### ISSUE THREAD

**Issue by bellemlj** [James-Thorson/VAST#70]
Hi Jim, 

I'm testing a CPUE series which has an 100% encounter rate for most of the years as it is a targeted fishery. The units are in fish per 1000 hooks. Can you give some guidance on the best input for the ObsModel vector? Is it possible to run the model on only the positive catches with a lognormal distribution, ignoring the zeros? Thanks!

**Comment by James-Thorson** [comment]
Have you read here:

https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/What-to-do-with-a-species-with-0%25-or-100%25-encounters-in-any-year

...?
