### ISSUE TITLE
Recommendation: Add error if estimating vessel effects with a single vessel

### ISSUE THREAD

**Issue by perretti** [James-Thorson/VAST#71]
Throw an error if there is only a single vessel in the dataset and vessel effects are being estimated. E.g., Data_Geostat$Vessel == 0 & OverdispersionConfig != c("Delta1" = 0, "Delta2" = 0)

**Comment by James-Thorson** [comment]
Thanks for pointing this out!  It is now added to branch `samples-as-sum-across-categories` and will be merged with main branch in the future.
