### ISSUE TITLE
Modelling presence-absence

### ISSUE THREAD

**Issue by hoyles** [James-Thorson/VAST#73]
Hi, we'd like to fit binomial presence-absence models. VAST has several distribution options including delta models, but I can't see an obvious way (i.e. an option for ObsModel[1]) to switch off the modelling of the positive component and just fit the binomial component. Is there a way to do this? 

I guess if all the positive responses are 1, then the model might estimate a flat response anyway and we could ignore the issue, but that approach might be unstable and would also add to the computational overhead. 

Thanks.

**Comment by James-Thorson** [comment]
Instructions for how to do this are now provided at the end of the User Manual in the development branch.
