### ISSUE TITLE
Specifying catchability covariates for encounter probability only

### ISSUE THREAD

**Issue by curryc2** [James-Thorson/VAST#75]
I am uncertain how to specify that a catchability covariate effect should be estimated for the encounter probability component of the delta-model, but not the positive catch rate component.

How does one ensure that lambda1_k but **not** lambda2_k is estimated within Build_TMB_Fn(), in the single covariate case?

**Comment by James-Thorson** [comment]
Thanks for asking, its not something that I built into the user interface directly.  However, it is easy to do and conceptually straight-forward given some basic TMB background.  It requires three steps which I'll sketch out here, and then you can respond if its still unclear.

```R
# Build TMB object:
TmbList = Build_TMB_Fn( ... ) # Where ... is your standard inputs

# Extract Map and modify it to turn off lambda2_k
Map = TmbList$Map
Map[["lambda2_k"]] = rep(NA, length(TmbList$Parameters$lambda2_k))

# Rebuild TMB object with user-specified Map
TmbList = Build_TMB_Fn( Map=Map, ... ) # where ... is the same stuff as above
```

The key is understanding that the `Map` input is passed as `map` to `TMB::MakeADFun`.  This `map` input expects a tagged list with any tagged element matching the name and length of an input in `parameters`.  To turn off a parameter, you just pass it an `NA` value in `map`.

Does this make sense?
