### ISSUE TITLE
Making short-term spatial density prediction using VAST

### ISSUE THREAD

**Issue by HaikunXu** [James-Thorson/VAST#76]
How to set up the data file or/and model configuration if we also want VAST to make short-term spatial density prediction (beyond the last year of observations)?

**Comment by James-Thorson** [comment]
You can do this by adding a new "dummy" observation to the set of data passed to `Data_Fn`, where this dummy observation occurs in any year you want to predict.  So for example, you could add another element to every vector passed to `Data_Fn` for this new "dummy" observation `b_i=NA` and `t_i` is equal to whatever year you want to predict (and elements e.g. `s_i`, `a_i` are also provided but their values don't particularly matter).  

Does this work?  If yes, please close the issue.

Also, I have added this feature recently and have not yet published it.  Could you please coordinate with me before including short-term predictions in a report or journal publication?  This is not something I expect for features that are already published and documented, but for new features I think it is useful to coordinate.

**Comment by HaikunXu** [comment]
Jim,

Thank you for your fast response. This method is exactly what I figured out before, but Data_Fn does not allow me to do so:

> TmbData = VAST::Data_Fn("Version"=Version, "FieldConfig"=FieldConfig, "OverdispersionConfig"=OverdispersionConfig,
+                         "RhoConfig"=RhoConfig, "ObsModel"=ObsModel, "c_i"=rep(0,nrow(Data_Geostat)),
+                         "b_i"=Data_Geostat[,'Catch_KG'], "a_i"=Data_Geostat[,'AreaSwept_km2'],
+                         "v_i"=as.numeric(Data_Geostat[,'Vessel'])-1, "s_i"=Data_Geostat[,'knot_i']-1,
+                         "t_i"=Data_Geostat[,'Year'], "a_xl"=Spatial_List$a_xl,
+                         "MeshList"=Spatial_List$MeshList, "GridList"=Spatial_List$GridList,
+                         "Method"=Spatial_List$Method, "Options"=Options)

Error in if (any(Prop_nonzero == 0 | Prop_nonzero == 1) & ObsModel_ez[1,  : 
  missing value where TRUE/FALSE needed


I realize that the elements of Prop_nonzero which correspond to the added years are NA so the model reports the error above. However, the model reports another error when I have fixed the issue above: 

Error in Data_Fn(Version = Version, FieldConfig = FieldConfig, OverdispersionConfig = OverdispersionConfig,  : 
  Please find and eliminate the NA from your inputs


Could you tell me how to deal with these errors that are caused by adding a dummy observation to data? Yes, I will coordinate with you when I decide to include this part in a publication.

Many thanks,
Haikun

**Comment by James-Thorson** [comment]
OK, thanks for your patience.  I just checked my code and see that I changed the interface to make it easier to do this for retrospective comparisons.  

Could you please build on your previous "dummy observation" implementation, but now include two dummy observations for each future year where one dummy observation has `b_i=0` and another has `b_i=1` (this is to satisfy the bug-checker in `Data_Fn` that you've got a mix of encounters and non-encounters in these future years).  Then use the `PredTF_i` interface to tell the model not to include the fit to the "dummy observations" in vector `b_i` in the objective function (its fit will instead by tracked in `Report$pred_jnll` which therefore will not be interpretable for short-term forecasts using dummy observations), where `PredTF_i=0` indicates data you're fitting and `PredTF_i` indicates data included in your crossvalidation test (in this case, the dummy observation for a future year).

Please also note that projections into years with no available data will only make sense when you have some structure on intercepts (i.e., `RhoConfig['Beta1']!=0` and `RhoConfig['Beta2']!=0`)

**Comment by HaikunXu** [comment]
The method you provided works well in making predictions. Thanks!

**Comment by HaikunXu** [comment]
One more question: what should I do if I also want to incorporate covariates into predictions? PredTF_i = 1 also removes the effects of the corresponding covariate on predicted encounter rate/positive catch, so simply doing does not allow the model to improve short-term predictions via utilizing robust covariate forecasts (e.g., seasonal SST forecast).

**Comment by James-Thorson** [comment]
Hmm.  I'm not sure I'm following, PredTF_i = 1 just excludes a given datum from being used in the joint likelihood, it doesn't affect interpretation of covariates.  To include covariates during short-term forecasts, you simply include input `X_xtp` in `Data_Fn` and the estimated relationship from data included in the likelihood (i.e., for `PredTF_i=0`) is then used for all years (including for years without any data included in the likelihood)

**Comment by HaikunXu** [comment]
Ah! I thought X_xtp needs to have the same temporal coverage as the data used to fit VAST, so didn't know how to input X_xtp for prediction years. Now I know that incorporating covariates into short-term predictions can be simply realized through adding those covariates (for prediction years) to X_xtp.
