### ISSUE TITLE
Rhoconfig switched with options in VAST manual

### ISSUE THREAD

**Issue by kvert-pre** [James-Thorson/VAST#77]
HI Jim, 

Just a note. In the VAST manual last version states that derived calculation are calculated in the Rhoconfig vector. I believe you meant to put Options vector as in the TMB code and R code ?
<img width="464" alt="screen shot 2018-01-30 at 2 32 12 pm" src="https://user-images.githubusercontent.com/30733215/35587006-6a84857c-05ca-11e8-84e0-99fd12455fe5.png">

**Comment by James-Thorson** [comment]
Thanks, I think I actually just fixed that this morning in the main branch.  But yes, please send along these fixes, there might be other typos too
