### ISSUE TITLE
Index_xcyl calculations

### ISSUE THREAD

**Issue by kvert-pre** [James-Thorson/VAST#78]
Hi Jim, 

The Index of abundance per species per site is converted from Kg to metrics tonnes in the TMB code right ? I was wondering then if you are using count data  you need to do Index_xcyl = D_xcy *a_xl ? Some of the function e.g. Index = SpatialDeltaGLMM::PlotIndex_Fn would then not work or would need to be corrected with Index *1000 ?

**Comment by James-Thorson** [comment]
Hmm.  Yes, I think the code is mis-labelling the output when using count data, and you'd need to multiple by 1000 to get an index in units "individuals".  I'm not planning to improve labelling or results for count-data models unless more people start using that feature.
