### ISSUE TITLE
add function to give current cpp version

### ISSUE THREAD

**Issue by wStockhausen** [James-Thorson/VAST#79]
It would be helpful to add a function that would give a character version of the current (latest) version of the cpp code, because it is a little hard to find (I originally thought it was the same as the version for VAST, but I eventually found it by looking in the "inst" directory under the package directory).

**Comment by James-Thorson** [comment]
A little investigation suggests that package `semver` is a good place to start for a function doing this, but it would need to be called from a wrapper function that (1) knows where to look for functions and (2) knows to strip off characters before the first number.  Anyway, I might take a crack at this later, although its not the top of the list

**Comment by wStockhausen** [comment]
Was just thinking it'd be something like
getVersion<-function(return("VAST_v4_0_0");)and you'd just update the
character string when you came out with a new cpp version. Course it would
be simpler to maintain if you could write the code to do it automagically.

Buck

***************************************************
* Dr. William T. Stockhausen                      *
***************************************************
* Resource Ecology and Fisheries Management       *
* Alaska Fisheries Science Center                 *
* National Marine Fisheries Service               *
* National Oceanic and Atmospheric Administration *
* 7600 Sand Point Way N.E.                        *
* Seattle, Washington 98115-6349                  *
***************************************************
* email: William.Stockhausen@noaa.gov             *
* voice: 206-526-4241 fax: 206-526-6723           *
* web  : http://www.afsc.noaa.gov                 *
***************************************************
All models are wrong, some are useful.--G.E.P. Box
Beware of geeks bearing equations.    --W. Buffett
***************************************************
Disclaimer: The opinions expressed above are personal
and do not necessarily reflect official NOAA policy.

**Comment by James-Thorson** [comment]
now added, see response to #30
