### ISSUE TITLE
Error message when trying to run the multi-species example

### ISSUE THREAD

**Issue by agruss2** [James-Thorson/VAST#80]
@James-Thorson I tried running the multi-species example, but got an error message. 
Therefore, I deleted the packages "VAST", "FishData", "SpatialDFA", "TMB", "TMBHelper", "SpatialDeltaGLMM", and "ThorsonUtilities" and tried re-running the multi-species example but still got the same error message:

> Species to include: Atheresthes stomias, Gadus chalcogrammus, Hippoglossoides elassodon
> Number of samples to include for each species: 201678
> Quitting from lines 148-150 (VAST--multispecies_example.Rmd) 
> Error in FUN(X[[i]], ...) : 'type' (character) of argument incorrect
> Calls: <Anonymous> ... <Anonymous> -> add_missing_zeros -> tapply -> lapply

Later today, I will try to understand what the issue with FishData::add_missing_zeros is. 
But, meanwhile, you may be able to quickly identify why I got the above-mentioned error message. 

Many thanks!

**Comment by zeroyin** [comment]
FYI, I have the same issue with this function so I organized the data myself.. I think they may have somehow changed some variable type in their data which caused this error.

**Comment by DanOvando** [comment]
Pull request [#7](https://github.com/James-Thorson/FishData/pull/7) over at `FishData` should fix this, but take a look and let me know if it doesn't. Some of the data was being converted from numeric to character, which was causing the error in `add_missing_zeros`

**Comment by James-Thorson** [comment]
OK, I think this is now fixed, see: https://github.com/James-Thorson/FishData/issues/6

**Comment by agruss2** [comment]
Yes, the multispecies example runs perfectly now and one gets all the expected outputs in the "VAST_output" folder. Thanks a lot to Dan, Curry and Jim !
