### ISSUE TITLE
Suggestion: Match t_yz to t_iz for seasonal models

### ISSUE THREAD

**Issue by perretti** [James-Thorson/VAST#81]
My (non-general) workaround:

```
# If this is a seasonal model, set the season to plot,
# and reduce the number of levels of the seasonal variable to 
# n-1 for model identifiability.
if (ncol(TmbData$t_iz) > 1){
  
  # Change t_yz to plot the appropriate season
  if (season2plot == "SPRING") {
    TmbData$t_yz[,2] <- max(TmbData$t_yz[,1] + 2) 
  }
  
  # Reduce levels for identifiability
  TmbData$t_iz[,2] <- 
    ifelse(!(TmbData$t_iz[, 2] %in% unique(TmbData$t_yz[,2])), 
           NA, 
           TmbData$t_iz[, 2])
}
```

**Comment by James-Thorson** [comment]
VAST should now "reduce levels for identifiability" automatically by fixing one intercept for the 2nd, 3rd, ... columns of `t_iz`, so the 2nd component here is no longer necessary.  I also don't see any general solution for which combinations of elements in `t_iz` to use when calculating outputs (as specified by `t_yz`).  But thanks for recording this topic on the issue tracker for future users!
