### ISSUE TITLE
recommend removing L83-85 in plot_factors function

### ISSUE THREAD

**Issue by zeroyin** [James-Thorson/VAST#82]
https://github.com/James-Thorson/VAST/blob/f0f931ddffee2d93f1a16753ddd6ef74debc523d/R/Plot_factors.R#L84

When I exclude spatial factors (*Omega1* and *Omega2*) the function plot_factors() returns error which traces back to this line eliminating elements in the list vector *L_List* instead of assigning a NULL value. Removing L:83-85 is recommended. I am running R version 3.4.3.

**Comment by James-Thorson** [comment]
I'm not sure I understand enough to act on this.  What do you mean "exclude spatial factors"?  And what function is throwing an error, and what is the error?

**Comment by zeroyin** [comment]
Sorry for the confusion. What I meant was, for example, if I run the model with 
`"FieldConfig" = c("Omega1" = 0,  "Epsilon1" = 2, "Omega2" = 0, "Epsilon2" = 0)`
When `Omega1 = 0` , this line of code (L84)
```
else{
      L_list[[i]] = NULL
    }
```
 removes the element and creates confusion in the index of the next element "Epsilon1" because `names(L_list)` is reduced to `c("Epsilon1", "Omega2", "Epsilon2")`.

**Comment by James-Thorson** [comment]
I still want the same length regardless of what is on or off in the model.  However, I have now done the naming of `L_list` at the end of the function such that it does not interact with adding `NULL` for missing elements.
