### ISSUE TITLE
Overdispersion random effects parameter names are inconsistent

### ISSUE THREAD

**Issue by hoyles** [James-Thorson/VAST#86]
The overdispersion parameters (random effects on catchability associated with vessels or tows) are labelled delta in the manual and the input options, but eta in the outputs. The variance parameters are L1_Z and L2_Z. This makes them difficult to identify - needs better description, or to be made consistent.

**Comment by James-Thorson** [comment]
The development branch now includes changes to the tutorials and User Manual to indicate that OverdispersionConfig (i.e., vessel effects) involves parameters `L1_z`, `L2_z`, `eta1_vf`, and `eta2_vf` which now matches the TMC code and output e.g., in `parameter_estimates.txt`
