### ISSUE TITLE
broken link to PDF of User Manual in README

### ISSUE THREAD

**Issue by taylori** [James-Thorson/VAST#87]
Just re-installed VAST to test issue #34 and noticed that [README.md](https://github.com/James-Thorson/VAST/blob/master/README.md) links to https://github.com/James-Thorson/VAST/blob/master/examples/VAST_user_manual.pdf which is no longer present. Easy to fix if your intention is to rely on .docx User Manual in `examples` but perhaps you have something new in the works in `vignettes`?

**Comment by James-Thorson** [comment]
Could you just change the link to the User_Manual.docx?

**Comment by James-Thorson** [comment]
sorry, you prolly can't change the README so I did it myself just now

**Comment by taylori** [comment]
Tried to do a pull request but by the time I merged your code it was done. Thanks.
