### ISSUE TITLE
Knot on an island when adding depth as a covariate

### ISSUE THREAD

**Issue by John-R-Wallace** [James-Thorson/VAST#92]
When adding depth as a covariate with the 'Mesh' method then, at least with Region = 'Other', a knot can land on an island.  This positive elevation (negative depth) of a knot can result in very large parameter values and extreme anisotropy.

See:
    https://github.com/John-R-Wallace/VAST_Examples_and_Scripts > Create a depth covariate using Imap::depthMeters()

The related issue under the Issue tab shows a figure of the island with the knot:
    VAST knot on an island in Southern California (in VAST_Examples_and_Scripts)

Setting the positive elevation to zero gave reasonable results. 

The knot on the island was slightly outside of the given latitude 'strata.limits' and, of course, was not within the depth limits.

**Comment by James-Thorson** [comment]
Good point, thanks for recording the potential issue here.
