### ISSUE TITLE
Covariate setup for constant covariate in multivariate model

### ISSUE THREAD

**Issue by perretti** [James-Thorson/VAST#94]
Following [this](https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/Adding-new-covariates), I'm trying to figure out how to setup the covariate matrix for a constant-in-time covariate, where the effect of the covariate should vary across categories. Param_Fn() appears to ignore categories when setting up gamma1_j: i.e., `gamma1_j = rep(0, ncol(DataList$X_xj)).` Should I be using X_xtp instead? If so, how?

Thank you.

**Comment by James-Thorson** [comment]
Have you seen `SpatialDeltaGLMM::format_covariates`?

If you have a multivariate model, then X_xtp will be the same as the univariate case, and VAST is designed by default to estimate a separate covariate effect for every slice `p` of `X_xtp` and for every category `c` (where `X_xtp` is assumed to be the same for every covariate)

**Comment by perretti** [comment]
The covariate is constant in time (e.g., Depth), so does that mean X_xtp should have duplicate columns for each slice? `SpatialDeltaGLMM::format_covariates` calculates a time-varying covariate only, correct?

I've been trying to use X_xj.

**Comment by James-Thorson** [comment]
yeah, please use X_xtp instead (X_xj is deprecated and should probably
throw an informative error).  You'll just have X_xtp[,t1,] = X_xtp[,t2,]
for all t1,t2, as you say

**Comment by perretti** [comment]
Great, thank you.
