### ISSUE TITLE
dependency of TMB package

### ISSUE THREAD

**Issue by kellijohnson** [James-Thorson/VAST#96]
The following line of code could be amended to `TMB::compile` to allow users to run the function without loading `TMB`.
https://github.com/James-Thorson/VAST/blob/654c513ddee0bf0bf3d52da83f26df38e7682b64/R/Build_TMB_Fn.R#L66

**Comment by James-Thorson** [comment]
I do it this way so that uses can overwrite the compile function eg using TMBdebug
