### ISSUE TITLE
Opt results 

### ISSUE THREAD

**Issue by kvert-pre** [James-Thorson/VAST#97]
Obj$env$parList(Opt$par)) to get Parhat does not seem to be working anymore. 
summary(Opt) shows 2 elements in the list , "opt" and "h". par is now under the Opt$opt list
Seems that the line to obtain Parhat should be changed to Obj$env$parList(Opt$opt$par)) ? 
Or is is a default that when the error message "model likely not converged" the SD are not given ?

**Comment by James-Thorson** [comment]
That happens when the hessian isn't positive definite, where it outputs h so you can inspect results. What happens if you try solve(Opt$h)?

**Comment by kvert-pre** [comment]
Opt$h is only have the names of the variable and no values. It is strange though as when I look at the final gradients they are in the 10^(-3), 10^(-5) range and the max gradient is 0.057. there is no message of non positive definite error only a "model likely not converged" error.

**Comment by James-Thorson** [comment]
Ultimately, `TMBhelper` is intended as a helper package and I encourage you to re-write it to learn more.  I'm not sure I understand why Opt$h is empty, so feel free to send me the RDA object for `Opt` and I could look briefly.

**Comment by kvert-pre** [comment]
Thank you.
